### ISSUE TITLE
Account creation: Unable to get to the dashboard on testnet

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1030]
### Steps to reproduce

1. Create new lisk id
2. Go through process of passphrase generation
3. Click 'Get to to your dashboard'

### Actual behaviour
Unable to connect the node popup
```
Warning: Can only update a mounted or mounting component. This usually means you called setState, replaceState, or forceUpdate on an unmounted component. This is a no-op.

Please check the code for the TransitionWrapper component

```
child of #812

**Comment by faival** [comment]
I think the same, and this is a released bug on 0.10.0 as it will happen the same thing, accounts can only be created in mainnet, as setting localhost or testnet will not call activePeerSet until one successfully logs in
