### ISSUE TITLE
Account is not being saved in local storage

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1031]
### Steps to reproduce

1. Login
2. Refresh app

### Actual behaviour
You are on a signin dashboard being not logged in

### Expected behaviour
You remain logged in

Child of #812

**Comment by faival** [comment]
@Efefefef , can you reproduce this behaviour in https://jenkins.lisk.io/test/lisk-hub/PR-1027/#/dashboard, if not, then please reference that this issue will be closed once that PR-1027 and issue #1022 are closed.
