### ISSUE TITLE
Activity: Delegate statistics: Delegates name is not shown instead of id

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1035]
### Steps to reproduce

1. Go to the delegate's acc with votes from named account, (devnet: 17110047919889272525L) 
2. Open Delegate statistics in Activity 
3. Look at Who voted

### Actual behaviour
Delegate's id
(devnet: 4401082358022424760L )

### Expected behaviour
Delegate's name

child of #812

**Comment by slaweet** [comment]
So the best solution is to use lisk-explorer as a data source for this, but that involves a lot of extra changes. E.g. being able to set explorer node when setting a custom node, setting up our Jenkins to run explorer node etc. So it won't be done in 1.0.0

**Comment by slaweet** [comment]
Cleaning up - Closing issues that were open for a long time without any update. We can re-open if needed.
