### ISSUE TITLE
Accounts: You can have listed 2 accounts of the same address in devnet

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1049]
### Steps to reproduce

1. Login in devnet
1. Login in devnet with same address one more time
1. go to /accounts

### Actual result
There are 2 accounts listed in the same time
In localstorage there is a diff:
 first with "peerAddress":"localhost:4000"
 second with "address":"localhost:4000" 

### Expected result
There should be only one acc in a list of accs

![image](https://user-images.githubusercontent.com/6704159/42870265-a21ebf3e-8a77-11e8-95a9-1dfba1857d50.png)

**Comment by slaweet** [comment]
Fixed in #1077

**Comment by Efefefef** [comment]
Reproducible
now 
first have "peerAddress":"localhost:4000"
second doesn't have "peerAddress" or "address"
