### ISSUE TITLE
Can't connect to node on Lisk Hub Version 1.0.0-rc.1

### ISSUE THREAD

**Issue by Aphiso** [LiskHQ/lisk-hub#1053]
### Expected behaviour
When entering my wallet seed I should be taken to my wallet.

### Actual behaviour
I'm getting an error message saying 'can't connect to node'. However, when I run Lisk Hub 0.10 I am able to connect just fine.

### Steps to reproduce
Open LH Version 1.0.0-rc.1 and enter seed phrase.

OS: Pop_OS 18.04/Ubuntu 18.04

**Comment by slaweet** [comment]
@Aphiso thank you for reporting the issue. It is, however, expected behavior for 1.0.0-rc.1, as was mentioned when announcing the release on gitter and lisk.chat:
> ... It is the first *release candidate* for version 1.0.0 which is the migration to Lisk Core 1.0.0 API. Therefore it currently doesn't work with Mainnet. ...

The release of the final Lisk Hub 1.0.0 will, of course, have to be coordinated with the release of Lisk Core 1.0.0 to Mainnet.
