### ISSUE TITLE
Activity: Account info: No votes of the account are present

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1057]
### Steps to reproduce

1. Login as not delegate
1. Vote for someone
1. Got to wallet -> account info

### Actual result
Votes are not present

### Expected result
Votes are there
![image](https://user-images.githubusercontent.com/6704159/42931174-46e66586-8b3f-11e8-82a0-e788903c10e8.png)

**Comment by slaweet** [comment]
Fixed in #1069
