### ISSUE TITLE
Enable opt-in analytics in user settings

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#1102]
### Expected behaviour

- Google analytics should not load api scripts by default
- Only when the user enables the setting: (requires design)
Then:
- An xhr request loads google scripts on head.
- google analytics is initialised with default tracking settings which can't be changed by js console (needs to be defined)

### Actual behaviour
- not implemented

**Comment by faival** [comment]
@slaweet 
We could internally host and maintain a MATOMO instance in order to assure we have complete control about the tracking data. 

https://developer.matomo.org/guides/tracking-javascript-guide

We would need an evaluation of the tool from dev-ops as well as an estimate on when this service could be available.

**Comment by slaweet** [comment]
MATOMO instance ready https://matomo.lisk.io/

**Comment by slaweet** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Evaluate effort to host Matomo](https://trello.com/c/397oPniS/211-evaluate-effort-to-host-matomo)

**Comment by osvaldovega** [comment]
Epic can be close, all subtask are implemented
