### ISSUE TITLE
Sending lsk to an address you never sent before

### ISSUE THREAD

**Issue by ducktank1990** [LiskHQ/lisk-hub#1124]
If you want to send lsk to an address you never sent before then there could pop-up a warningbox:

> "It´s the first time you gonna send to "xxxxxL - click transfer"

User can decide to activate this or not. 
In the future this could be a part of a "secure tx"-option

It helps users to not make mistakes.

In RL some trustless user would first send 0.2 lsk to test/insert "new address"
-> if the lsk arrived -> the user send the rest of the amount and if the warningbox does not pop-up then the user can click transfer without an adrenaline-kick :)

**Comment by reyraa** [comment]
I think bookmarks eliminate the need for this feature.
