### ISSUE TITLE
Formalise strategy for Mocha to Jest migration

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#1134]
### Expected behaviour

- both stages run while migrating.
- components which require modifications are upgraded to Jest

- possible drawback of increasing build time while migrating
```
- Mocha excludes tests which are run by Jest stage
- Jest excludes tests which are run by Mocha stage
- Once Mocha excludes all tests the stage can be removed
```

**Comment by slaweet** [comment]
To Prevent increasing build time, I just found out that Jenkins can run stages in parallelhttps://jenkins.io/blog/2017/09/25/declarative-1/

So we hopefully can run Jest and Mocha stage in parallel.
