### ISSUE TITLE
e2e fails asserting number of rows in transaction table 

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1138]
### Steps to reproduce
Running e2e send.feature 
Scenario: should allow to send when enough funds and correct address form
sometimes fails on step:
And I should see 25 rows

### Actual result
Sometimes its 26 because pending transaction is there, sometimes its 25 cause sent transaction was already approved

**Comment by slaweet** [comment]
Fixed in #1140
