### ISSUE TITLE
Clean up Jenkins Webpack unit test build output

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#1145]
### Actual behaviour
lisk-elements shows some error logs related to user-agent, 
once this issue is fixed in lisk-elements and  lisk-hub updates the dependency, there should not be a vast amount of logs along our e2e-tests
https://github.com/LiskHQ/lisk-elements/issues/696

### Steps to reproduce

**Comment by slaweet** [comment]
Solved by migrating e2e tests from cucumber to cypress
