### ISSUE TITLE
Lisk Hub v0.10.0 died on me

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-hub#1150]
I had just transfered some LSK from wallet to wallet. Then I pressed the Dashboard button in the top left and it showed the message 'unable to show page' or something like that in the middle of the screen. 
Then nothing worked anymore and I wanted to exit the program. After relaunching it only showed me this and it doesnt work anymore.
![image](https://user-images.githubusercontent.com/20902562/43951573-c6c221fe-9c93-11e8-8fc2-8946d4a8cb8b.png)

**Comment by Joo5t** [comment]
Hi slaweet, Sorry for my late reply. I will now keep a closer eye on this ticket. 
I downloaded the latest version to test things again. Still no luck. Is there a parameter I can use to reset something? I already uninstalled various times and tried other versions. Lisk Nano works fine. Im running Windows 10. 
![image](https://user-images.githubusercontent.com/20902562/44796947-627fc500-abae-11e8-8847-4b2d132a109b.png)

**Comment by slaweet** [comment]
Hi @Joo5t ,
Thanks for the screenshot. There is one more thing you could do to help us - after opening dev tools (ctrl+shift+i), switch to the "Console" tab and make a screenshot if there is any red error in there.

When you're in the console, you can clear local storage by executing the following command:
``` 
localStorage.clear()
```
That should reset any saved state.

**Comment by Joo5t** [comment]
Thank you for researching this issue. Here is the screenshot. 
![image](https://user-images.githubusercontent.com/20902562/45078772-21793a80-b0f1-11e8-9de4-cf3950e0cef1.png)

When I enter localStorage.clear() it gives me an undefined reply. 

I will visit HQ next tuesday 11 september and will be in the office from 13.00 to 17.00, so I could walk over and show you my laptop.
