### ISSUE TITLE
Add reference field to specific amount LSK request

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#1154]
Add Reference Field to Request Lisk Amount
Requirements:
- Reference field validation check
- Reference field should appear in the confirmation step
- Reference field value should be added to url on confirmation step

**Comment by Efefefef** [comment]
What are req for validation reference field?

**Comment by slaweet** [comment]
@Efefefef the length is up to 64 bytes, so max 64 characters, and even less if multi-byte Unicode chars are used.
