### ISSUE TITLE
CustomNode address should provide validation errors

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#1159]
### Expected behaviour
- validation should account for malformed urls
- when a valid address is used, peer actions should not post process address url.
- should be possible to login with urls such: https://94.237.41.191, 94.237.41.191:7000
### Actual behaviour
- not possible to login with https://94.237.41.191, no validation errors are shown for e.g. space chars in url.

**Comment by Efefefef** [comment]
we consider `localhost:4000` invalid url but Login button gets enabled and you get an error logging in
