### ISSUE TITLE
Improve login page testing/dev experience

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1187]
### Expected behaviour
- Login page should remember last used network and address (in localStorage)

- It should be possible to save passphrase and auto log in as it used to work in Lisk Nano: https://github.com/LiskHQ/lisk-nano/blob/fccb2bc79df915893852e62f23efef293afa3e68/README.md

> For ease of development, you can setItem in localStorage to prefill a passphrase, e.g.:
> ```
> localStorage.setItem('passphrase', 'wagon stock borrow episode laundry kitten salute link globe zero feed marble')
> ```
> 
> And then you can setItem in localStorage to login automatically
> ```
> localStorage.setItem('autologin', true)
> ```

- it should allow to autolog in public,private pages
- it will allow to specify URL for peer to connect to

### Actual behaviour

After removing saved accounts, it anoying to always log it and always select network.

**Comment by faival** [comment]
https://github.com/LiskHQ/lisk-nano/blob/fccb2bc79df915893852e62f23efef293afa3e68/src/components/login/login.js#L120

**Comment by faival** [comment]
@slaweet @Efefefef , what happens with pages which do not require login? should one be autologged in also?, I propose to only after going to a private page visit, then you'll be logged in also on public ones.

(e.g.)
```
/dashboard --> NOT logged in
/wallet --> logged in
/dashboard --> logged in
```
