### ISSUE TITLE
Request: Not prefilled launch link in the proposed request emaill

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1189]
### Steps to reproduce

1. Go to Request tab in wallet/dashboard
1. Click `Send request via E-mail`
1. Or click `Request Specific Amount` and then `Send request via E-mail `
1. Wait for email app to load
1. Check out the launch link inside mail body

### Actual result
lisk://wallet

### Expected result
Link with a recipient or recipient and amount

![image](https://user-images.githubusercontent.com/6704159/44263317-b984b200-a21e-11e8-830b-c1e43d310646.png)

**Comment by michaeltomasik** [comment]
I tried to reproduce it on 1.3.0 but I couldn't
<img width="821" alt="screen shot 2018-09-09 at 20 09 48" src="https://user-images.githubusercontent.com/7786627/45267429-67752c00-b46c-11e8-885c-eebffde636e0.png">

**Comment by Efefefef** [comment]
The problem is the mailto link is not url encoded , so ? and & or &amp; gets truncated when sending the link to some web app like gmail
![image](https://user-images.githubusercontent.com/6704159/45300445-a360cd80-b50e-11e8-96ea-ab848b240bee.png)
