### ISSUE TITLE
Styling of network switcher on Sign In

### ISSUE THREAD

**Issue by hpbaxxtr** [LiskHQ/lisk-hub#1194]
Designs on the left, Hub v1.1.0-rc.1 on the right.
### Initial state
<img width="400" alt="screen shot 2018-08-21 at 09 37 59" src="https://user-images.githubusercontent.com/34156128/44387858-f5718d00-a526-11e8-92c6-f18ed33ef9d9.png">
"Network to connect to" should be Open Sans Regular

### Dropdown
<img width="400" alt="screen shot 2018-08-21 at 09 38 16" src="https://user-images.githubusercontent.com/34156128/44387993-4bdecb80-a527-11e8-8b05-31e6af0f5182.png">
Networks should be Open Sans Regular, Close X icon is missing.

**Comment by bmaggi-lisk** [comment]
Adding the "X" symbol next to the label is quite difficult because this is custom component from react-toolbox
