### ISSUE TITLE
Alignment of bottom sidebar navigation elements

### ISSUE THREAD

**Issue by hpbaxxtr** [LiskHQ/lisk-hub#1195]
### Alignment & icon sizes
Elements are correctly left aligned, but the container of bottom sidebar navigation should be center aligned to the sidebar, and Icons are too small. https://taikonauten.invisionapp.com/d/main/#/console/12665756/284010744/inspect 
Design on the left, Hub v1.1.0-rc.1 on the right. 

<img width="400" alt="screen shot 2018-08-21 at 09 39 44" src="https://user-images.githubusercontent.com/34156128/44388218-dd4e3d80-a527-11e8-9b2b-c30448a9b5ee.png">

**Comment by slaweet** [comment]
![screen shot 2018-10-08 at 15 12 36](https://user-images.githubusercontent.com/1254342/46610983-a9959a00-cb0c-11e8-9514-a485bf8403d8.png)
It also shouldn't go over the top menu items on a smaller screen height, but rather the top menu items should have a scroll container that ends above the bottom items (Settings, Help)
