### ISSUE TITLE
Update Jenkins to run against lisk-core 1.1.0

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1202]
### Expected behaviour
Jenkins should run against lisk-core 1.0.1
### Actual behaviour
Jenkins runs against lisk-core 1.0.0-rc.1

**Comment by faival** [comment]
being this time, will update requirement to run hub against core 1.0.0

**Comment by slaweet** [comment]
Updated title to use core 1.1.0
