### ISSUE TITLE
Network indicator is not shown if 'Switch Networks' is off 

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1251]
### Steps to reproduce

1. Turn on 'Switch Networks' in settings
1. Login in test or dev net
1. Turn off 'Switch Networks'
1. Logout

### Actual result
Network indicator disappears
In a logged out state, I have an impression I am searching in mainnet

### Expected result
Network indicator is not dependant on 'Switch Networks'

**Comment by slaweet** [comment]
I originally (https://github.com/LiskHQ/lisk-hub/issues/1103) thought it should work as it does, but Andrei is right that testnet/custom node should be displayed always. Only Mainnet should depend on the show-network-swicher setting.
