### ISSUE TITLE
Transaction totals/statements between specific dates. 

### ISSUE THREAD

**Issue by mmguide2003** [LiskHQ/lisk-hub#1256]
I believe it would be useful to have the ability to create a bespoke statement with a total between given dates. I have been forced to manually add up transactions for a monthly perspective of reward payouts and this is rather cumbersome.
e.g. the form choices could include:

Start date:
End date:                    
incoming/outgoing/net

Producing a list with the Total at the top (and bottom) for easy viewing in larger statements. 

This would be similar to online banking options and would be helpful for many users.

**Comment by michieldespiegelaere** [comment]
an example about what @mmguide2003 means.

Date selection
![image](https://user-images.githubusercontent.com/17978514/45149087-11cd2500-b1c9-11e8-9a16-20423e523288.png)

incomming and outgoing tx's
![image](https://user-images.githubusercontent.com/17978514/45149187-43de8700-b1c9-11e8-9790-acc170dd3289.png)

It would also be usefull to filter on certain addresses as you can see in the first screenshot.

**Comment by mmguide2003** [comment]
As above, but with a **net total** for the period at the top and bottom of the list of transactions (for user-friendliness on longer lists). This is the main feature from my point of view, as it enables you to track account progress, particularly if you use your address to receive voting rewards.

**Comment by slaweet** [comment]
Filtering by date will be soon implemented in https://github.com/LiskHQ/lisk-hub/issues/1666 so closing this issue.
