### ISSUE TITLE
Onboarding text change: Saved IDs

### ISSUE THREAD

**Issue by hpbaxxtr** [LiskHQ/lisk-hub#1259]
<img width="500" alt="screen shot 2018-09-06 at 16 29 37" src="https://user-images.githubusercontent.com/34156128/45164155-283ba680-b1f2-11e8-9b36-d25109f4bf7e.png">

Onboarding text still talks about the old account switcher.

**Comment by michaeltomasik** [comment]
Part of https://github.com/LiskHQ/lisk-hub/issues/1141
