### ISSUE TITLE
Uppercase characters allowed in Delegate name

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-hub#1261]
### Expected behaviour

Error message should appear when entering Uppercase characters in the Delegate name registration window in lisk-hub.

### Actual behaviour

Uppercase characters allowed, the final step throws an error (big red cross).

### Steps to reproduce

Goto delegate registration and enter a name with UPPERcase characters.

### Notes
Registering a name with Uppercase characters using the api throws the following, correct, error "Error: Status 409 : Username must be lowercase"

**Comment by slaweet** [comment]
@Korben3 Thank you for the report. We already had another ticket https://github.com/LiskHQ/lisk-hub/issues/1211 for this problem and it is now fixed in just released version `1.3.0-beta.1`, so I'm closing this issue.
