### ISSUE TITLE
boolean in place of function onClick and userAgent console errors 

### ISSUE THREAD

**Issue by Altanaib** [LiskHQ/lisk-hub#1263]
Have been looking at these glaring console errors 

`Warning: Expected `onClick` listener to be a function, instead got `false`.

If you used to conditionally omit it with onClick={condition && value}, pass onClick={condition ? value : undefined} instead.`

and 

`bundle.app.js:61350 Refused to set unsafe header "User-Agent"`

**Comment by osvaldovega** [comment]
Issue fixed in PR #1473
