### ISSUE TITLE
Refactor autosuggest component for use in address book autocompletion 

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#1266]
Search autosuggest and bookmark autosuggest components are similar, so they could have some common code.

**Comment by michaeltomasik** [comment]
Moved for now
Reason - Lack of design
We will wait until We have more features, use cases so our implementation will cover more components

**Comment by slaweet** [comment]
Cleaning up - Closing issues that were open for a long time without any update. We can re-open if needed.
