### ISSUE TITLE
Second passphrase registration: Ugly timestamp error

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1278]
### Steps to reproduce

1. Set your system time ahead of the current actual time
1. Got to settings
1. Register second passphrase

### Actual result

Error message is ugly
Clicking OK does nothing

### Expected result

Nice error message on style

### Version

1.2

### Screenshot (if appropriate)
![image](https://user-images.githubusercontent.com/6704159/45431504-1ea9b700-b6a8-11e8-9302-316472381090.png)

**Comment by bmaggi-lisk** [comment]
@slaweet Can you post design mock for the view ?

**Comment by slaweet** [comment]
@bmaggi-lisk here you are https://taikonauten.invisionapp.com/d/main/#/console/12665756/284020037/preview
