### ISSUE TITLE
Transactions to 'yourself' are all seen as "account initialization"

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-hub#1281]
If you send a transaction to yourself using the hub, they are all seen as "account initialization", this look weird/wrong. If an initialization has already performed, the message shouldn't be repeated.

### Steps to reproduce

Use the hub to send lisk to your **own** address.

### Actual result

Address is mentioned as "account initialization"

### Expected result

Address should mention the senders address. 

### Solution

Save locally if an "account initialization" is performed. After the first time the hub should mentioned the senders address, even though its the same as the receiver.

### Screenshot (if appropriate)
![image](https://user-images.githubusercontent.com/42899281/45455556-d316fd80-b6e7-11e8-86c4-522aa8e97870.png)

**Comment by slaweet** [comment]
I agree that it is confusing. However, it is not trivial to always know if a transaction is the first incoming transaction. For example, there can be 1000 incoming transactions and account initialization at the end, but to be sure that the there was no account initialization in between those 1000 transactions, I'd have to fetch all of those from a node, which is a lot of unnecessary traffic.  

Now with the reference field, I would rather set "Account initialization" reference when doing the account initialization and always show the address.
