### ISSUE TITLE
Refactor TransactionsDetailView component

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1282]
It is too big and there are some other issues described in https://github.com/LiskHQ/lisk-hub/pull/1273/

**Comment by michaeltomasik** [comment]
Suggested refactoring:
Refactor by setting const fields to display per transaction type in a separate file and then render it in 2 columns.
```
{
    transactionType: TransacitionType.send,
    fields: [ 'date', 'recipient', 'senderId'],
}
```
