### ISSUE TITLE
"Confirm transfer" truncates the reference field

### ISSUE THREAD

**Issue by Nimbus76** [LiskHQ/lisk-hub#1285]
The "Confirm transfer" screen truncates the reference field.  A confirmation screen should include all reference field data so the accuracy of the proposed transaction can be confirmed.

### Steps to reproduce
Create a transaction in Hub with a long reference field entry and "Send"

### Actual result
"Confirm transfer" screen will truncate the reference field and not include the entire reference data.

### Expected result
"Confirm transfer" screen should show the all reference field data for the proposed transaction.  Longer entries should wrap to the next line if necessary.

### Version
1.3.0-beta.1.  Windows 10 OS.

### Screenshot (if appropriate)
![truncated](https://user-images.githubusercontent.com/32406458/45599481-e1983a00-b9b1-11e8-9d5d-1266f8d0c882.PNG)

**Comment by slaweet** [comment]
@Nimbus76 Thank you for reporting this issue.

@michaeltomasik the solution should be as easy as making the reference field multiline.
