### ISSUE TITLE
delegateCache in localStorage have undefined object property

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#1296]
### Steps to reproduce

1. I was using app then I wanted to check localStorage. And I discovered delegateCache have a wrong property name
Details to be provided...
### Version

Mac High Sierra

### Screenshot (if appropriate)

![screen shot 2018-09-21 at 07 51 13](https://user-images.githubusercontent.com/7786627/45863797-115f8d00-bd78-11e8-9fd2-718fb0972222.png)

**Comment by slaweet** [comment]
This issue seems to be making another issue more likely: https://github.com/LiskHQ/lisk-hub/issues/1359

The fix of both should likely be almost the same.

**Comment by slaweet** [comment]
Fixed in #1451
