### ISSUE TITLE
Release with homebrew-cask for MacOS users

### ISSUE THREAD

**Issue by yutarot** [LiskHQ/lisk-hub#1298]
---
name: Release lisk-hub with homebrew-cask
about: It makes MacOS/homebrew users more comfortable to be involved with the app

---

### Description of the problem

I am a new user of lisk-hub and I am using MacOS.
Also, I am using homebrew to manage applications on my machine.

Do you have any plan to release the application with homebrew-cask for MacOS?
https://github.com/Homebrew/homebrew-cask
If no, then would it be possible to make it happen?

I think it would be great if we could get/manage lisk-hub more easily with homebrew-cask.

### Suggested solution

Add lisk-hub release to homebrew-cask

**Comment by slaweet** [comment]
Cleaning up - Closing issues that were open for a long time without any update. We can re-open if needed.
