### ISSUE TITLE
Add support for Trezor hardware wallets

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#1319]
## Story: As an owner of Trezor hardware wallet, I'd like to be able to use my Trezor to send LSK and vote for delegates

1. I should be able to select "Login with Trezor" as the login option in addition to "Login by Passphrase"
2. When I select "Login with Trezor", there can be one or more LSK accounts stored on the device. The addresses and avatars of the accounts are determined by the master seed (passphrase) of my device, so I cannot choose what they will be.
2. In order to be able to access the accounts stored on the hardware wallet, (1) the device must be connected and (2) the device must be unlocked by PIN. If (1) or (2) is not met when I select "Login with Trezor", Lisk Hub inform me about what I need to do (that is (1) or (2)) and show the list of accounts only after conditions (1) and (2) are met. Note that this is different in Ledger, where also "Lisk" app must be opened on the device.
2. Entering PIN is different on Trezor Model T and Trezor One. On Trezor Model T this happens entirely on the touch screen of the device, however, Trezor One doesn't have a touch screen and thus Hub needs a screen for entering a PIN as described in [Trezor User Manual](https://wiki.trezor.io/User_manual:Entering_PIN)
3. I must be able to add another account to the device only if all accounts on the device are already used (have some transactions)
4. I must be able to log in to any of the accounts stored on my device.
4. When selecting an account to log into, I have to confirm the address on my device before proceeding in Hub. Note that this is only the case for Trezor (not Ledger)
5. When logged in with Trezor account, I can use Hub as with a normal passphrase account, with these exceptions:
- 2nd passphrase registration is not allowed, because it doesn't provide more security if the 2nd passphrase is derived from the same hardware wallet.
- Delegate registration is not allowed, because it's not possible to run a node on a hardware wallet
- Send LSK and Vote transactions have to be confirmed by performing an action with the hardware device - it can be accepted or rejected on the device.
- Logout can be also caused by disconnecting the Trezor device (in addition to logout from the UI).

## Login flow
![Screen Shot 2019-03-29 at 14 54 21](https://user-images.githubusercontent.com/1254342/55237509-9bf6dc80-5232-11e9-9acd-5d81e3968591.png)

**Comment by Efefefef** [comment]
@reyraa 
1. What if more then one wallet of the same type are connected? Should we show them all at Select device screen? How the user will differentiate between them?
1. Story's desc contains "Login with Trezor" button instead of more general purpose "Login with Hardware Wallet"
1. There is no 'Loading accounts' screen in new designs
1. There is no req for the Confirm on device and Disconnected screens for Tresor
