### ISSUE TITLE
Only first 10 votes are displayed

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1325]
### Steps to reproduce

1. Open Hub
1. Search for `6853061742992593192L`
1. Go to "Delegate statistics"

### Actual result

It shows only 10 votes and 10 voted delegates. Because Lisk Core 1.0.0 returns only 10 by default, whereas 0.9.X used to return all of them.

### Expected result

It should show 101 voted delegates and over 10K votes as explorer shows:

https://explorer.lisk.io/delegate/6853061742992593192L

### Version

Lisk Hub 1.0.0 and higher

### Screenshot (if appropriate)

![screen shot 2018-10-08 at 11 19 20](https://user-images.githubusercontent.com/1254342/46600938-0b91d780-caec-11e8-96cf-4009836e45ed.png)

**Comment by Efefefef** [comment]
@Efefefef unskip tests in activity.spec after fixing

**Comment by Efefefef** [comment]
Reopen because Account tab shows only 10 votes

**Comment by punkr0ck** [comment]
The section "Who voted for this delegate" is still bugged and is showing only 10 entries.

**Comment by Efefefef** [comment]
@punkr0ck Yes, we will address this issue in #1344
