### ISSUE TITLE
Registration: Custom node reg always falls back on localhost:4000

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1326]
### Steps to reproduce

1. Run lisk core not on the 4000 port
1. Choose Custom Node
1. Enter Url on which you are running core
1. Walk through the registration process

### Actual result

Error popup: Unable to connect to node
Hub tries to connect to localhost:4000

### Expected result

Appear logged in devnet on specified port

### Version

1.3, 1.4

**Comment by slaweet** [comment]
### Specification
- Custom node URL should be validated (try to connect to it) on login page when clicking "Create Lisk ID"
- If the request is successful, then go to the first step of creating a new account
- If the request fails, then show "Unable to connect the node" error toast and stay on the login page
- If network is not custom node, then clicking "Create Lisk ID" doesn't check the mainnet/testnet URL and goes directly to the first step of creating a new account
