### ISSUE TITLE
Use different icon for external and internal links

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1330]
Links that go outside of the app should have a different arrow icon

<img width="907" alt="screen shot 2018-08-24 at 12 40 05" src="https://user-images.githubusercontent.com/1254342/46670096-884ab180-cbd1-11e8-9214-28b4fd734873.png">

https://taikonauten.atlassian.net/browse/L20-528

**Comment by slaweet** [comment]
Technically I would create a "Link" component that can automatically detect if the link is just a path or includes `http(s)//:...`

**Comment by bmaggi-lisk** [comment]
@slaweet The current list of icons does not include the font we need to show for external links
![image](https://user-images.githubusercontent.com/43953571/47295219-6872af00-d60f-11e8-980e-1865c34b9f1b.png)

**Comment by bmaggi-lisk** [comment]
Assets: https://drive.google.com/drive/folders/1h5HzWxbRXLlSfW-x3NnEHKgqp3R_keHR
