### ISSUE TITLE
Remember selected network

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1337]
### Description of the problem

If I wan't to use testnet or custom node most of the time, it is annoying to always select in login page.

### Suggested solution

- Login page should save the last used network (and address) in localStorage. 
- This network should also be used as the default network without logging in.
- It should use the same localStorage for storing the network as autologin uses. 
- if the stored nework is not accessible when launching the app, then default to mainnet

**Comment by punkr0ck** [comment]
It doesn't work anymore.
