### ISSUE TITLE
Only first 10 voters are displayed

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1344]
This is a follow-up to https://github.com/LiskHQ/lisk-hub/issues/1325

It turned out that fixing voters is more complex because with the current API we cannot keep the functionality

### Specification

- "Who voted for this delegate" should show the correct number 
- Only first 100 items are fetched at first
- Keep currenty ipmemented behaviour: only first 35 are displayed at first, rest after clicking "Show more"
- Further items are fetched with infinite scroll
- "Filter votes" functionality should be removed because the new API doesn't allow to do this.

**Comment by punkr0ck** [comment]
> "Filter votes" functionality should be removed because the new API doesn't allow to do this.

Without the ability to search through the "Who voted for this delegate" section is useless now. No one will scroll through hundreds and thousands of accounts to check who voted for delegate xy.
