### ISSUE TITLE
Change font color of BTC/LSK chart timestamps

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-hub#1347]
The timestamps in the BTC/LSK chart are very hard to read because the font color is the same as the chart gradient (see attached snippet).

### Expected result
Change the font color to white (or any other high contrasting color) to make it more readable.

### Version
Lisk Hub 1.3.0 (Windows)

### Screenshot (if appropriate)
![lish hub dashboard btc lsk chart](https://user-images.githubusercontent.com/25596204/46868940-7879da00-ce2a-11e8-9065-d8b5e8da01b6.PNG)

**Comment by slaweet** [comment]
@Lemii  Thank you for the feedback. Why tried some colors, anything bright makes the graph stand out too much. So we'll make the labels darker to `#2C4062`
