### ISSUE TITLE
Unable to register as a delegate with an account balance of 25

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-hub#1350]
### Steps to reproduce

1. Create a new address with a lisk balance of 25
2. Login to that address and register  as a delegate.
3. An error: "Insufficient funds (Fee: 25 lisk)" is displayed

### Actual result
Unable to register as a delegate. (the same action works fine in nano).

### Expected result
Able to register as a delegate.

### Version
Hub 1.3.0

### Screenshot (if appropriate)
![image](https://user-images.githubusercontent.com/42899281/46903422-e084fa80-ced4-11e8-962b-67905f6565f2.png)

**Comment by slaweet** [comment]
Thanks for the report. Looks like the problem is that the condition is "More than 25 LSK" instead of "At least 25 LSK"
https://github.com/LiskHQ/lisk-hub/blob/1b88a00154b8d4bfc8d698ad803b2713f36587f4/src/components/registerDelegate/steps/choose/choose.js#L26-L29

**Comment by Korben3** [comment]
No problem, that looks like an easy fix.
