### ISSUE TITLE
Search: Delegate search occur not waiting results to be fetched

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1351]
### Steps to reproduce

1. Enter existing delegate name into the search field
1. Immediately press enter

### Actual result

No results

### Expected result

Delegate account page
App should wait for results being fetched, then show results

### Version

1.3, 1.4, 1.5

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/46939296-3d63ea80-d066-11e8-9d1f-79627fa8c196.png)

**Comment by Efefefef** [comment]
@Efefefef Unskip test in `search.spec` after fix

**Comment by slaweet** [comment]
To solve this problem in a nice way, we should keep track of when a search request is in progress and display a "Searching..." message.
 Currently, it displays "No results found" message when a search request is pending.
