### ISSUE TITLE
Search: Search input get squeezed when window size < 1400

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1353]
### Steps to reproduce

1. Reduce the width of the app window to less or equal 1400
1. Look at the search field

### Actual result

Squeezed in left angle

### Expected result

Space in the header should be used better

### Version

1.3 , 1.4, 1.5

### Screenshot (if appropriate)
/> 1400

![image](https://user-images.githubusercontent.com/6704159/46940231-89179380-d068-11e8-9315-d63c23121eb7.png)

<1400

![image](https://user-images.githubusercontent.com/6704159/46940238-8c128400-d068-11e8-96c7-fbd7728ee528.png)

**Comment by slaweet** [comment]
Part of the fix should also be to make sure that the `X` button doesn't overlap the search term and has the same color as search term
![screen shot 2018-10-15 at 11 11 01](https://user-images.githubusercontent.com/1254342/46941284-152aba80-d06b-11e8-896e-3bf63b42d474.png)
