### ISSUE TITLE
Show the actual error in login error toast

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1357]
### Description of the problem

Sometimes tests are failing because of some connection error
It is scary and uncertain what was the actual error

![image](https://user-images.githubusercontent.com/6704159/46960162-2ccf6680-d09e-11e8-96e8-0406a85e9422.png)

### Suggested solution

Would be helpful to show the error to know if it is a typo or too many requests or server is down
And its not bad to show more verbous message to the user

**Comment by 4fryn** [comment]
+1 yes please :)

**Comment by michaeltomasik** [comment]
I have an issue related to this https://github.com/LiskHQ/lisk-hub/pull/1274

**Comment by slaweet** [comment]
### Specification
- If the response contains an error message, then it should say `Unable to connect to the node, Error: {message}, Status code: {code}`
- If the response doesn't contain an error message, then it should say `Unable to connect to the node, Status code: {code}`
- If no response, then it should say `Unable to connect to the node, no response from the server.`
