### ISSUE TITLE
delegate API requests fail with "check spelling - name does not exist on mainnet"

### ISSUE THREAD

**Issue by 4fryn** [LiskHQ/lisk-hub#1359]
### Steps to reproduce

1. go to a votemanager, i.e., https://lisk.builders/votemanager or http://uncartel.4fry.net/
1. select at least 33 delegates to vote/unvote for
1. click on step 1
1. log into lisk hub
1. see how all the delegates are being fetched from the API
1. eventually these requests fail and result in "check spelling - name does not exist on mainnet"

### Actual result

See above and https://github.com/lisk-builders/lisk-builders/issues/63

### Expected result

Be more graceful about fetching the delegates from API, these names obviously exist on mainnet

### Version

Hub 1.3.0-rc1, Ubuntu 18.10

### Screenshot (if appropriate)

![screenshot at 2018-10-16 10-40-38](https://user-images.githubusercontent.com/26774427/47003736-3c978b00-d130-11e8-9bec-04ec38510baf.png)

**Comment by Efefefef** [comment]
@Efefefef Resolve e2e TODO after fix
