### ISSUE TITLE
Jenkins sometimes fails because "port is already allocated"

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1386]
Jenkins sometimes fails because of this error:

```
[cypress] ERROR: for pr1377_lisk_1  Cannot start service lisk: driver failed programming external connectivity on endpoint pr1377_lisk_1 (23e6c47bd1118851d95c1d438d4cb5bc8b5e14f969f6310b2fae2e8e59319335): Bind for 0.0.0.0:5000 failed: port is already allocated
[cypress] 
[cypress] ERROR: for lisk  Cannot start service lisk: driver failed programming external connectivity on endpoint pr1377_lisk_1 (23e6c47bd1118851d95c1d438d4cb5bc8b5e14f969f6310b2fae2e8e59319335): Bind for 0.0.0.0:5000 failed: port is already allocated
```
https://jenkins.lisk.io/job/lisk-hub/job/PR-1377/2/consoleFull

I think it's related to running two builds in parallel on one Jenkins node.

**Comment by Efefefef** [comment]
@fchavant Hi! Need your help here
In lisk-core docker-compose.yml we have the following mapping:
`   ports:
      - ${ENV_LISK_HTTP_PORT}:${ENV_LISK_HTTP_PORT}
      - ${ENV_LISK_WS_PORT}:${ENV_LISK_WS_PORT}`
Can we check if the port is allocated and if so increment the env variable?

**Comment by fchavant** [comment]
@Efefefef this should do the trick: https://jenkins.lisk.io/job/lisk-hub/job/PR-1377/20/replay/diff
(not specifying a port mapping will lead to a random port being picked instead)

**Comment by Efefefef** [comment]
@fchavant We also need to pass the host port to the command located below
`export CYPRESS_coreUrl=http://127.0.0.1:$( docker-compose port lisk 4000 |cut -d ":" -f 2 )`

**Comment by Efefefef** [comment]
@fchavant Do you maybe have mac compatible version of sed command?

**Comment by fchavant** [comment]
> @fchavant We also need to pass the host port to the command located below
> `export CYPRESS_coreUrl=http://127.0.0.1:$( docker-compose port lisk 4000 |cut -d ":" -f 2 )`

We already have that in the `Jenkinsfile`.

> @fchavant Do you maybe have mac compatible version of sed command?

You could try to `brew install gnu-sed` and then use `gsed` instead of `sed`. Another option would be to use `yq`. Anyway this'll run on Jenkins (Linux).

**Comment by fchavant** [comment]
@Efefefef this works: https://jenkins.lisk.io/job/lisk-hub/job/PR-1377/23/replay/diff

**Comment by Efefefef** [comment]
@fchavant Thank you
