### ISSUE TITLE
Balance shows 0 if the value has not been already fetched

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1391]
### Steps to reproduce

1. Sometimes during signing in it happens that api call takes a bit more time
1. I get to the dashboard

### Actual result

Balance shows 0 before it receives the fetched value
That might be enough for heart attack
Sometimes it takes even longer, so e2e test fails.

### Expected result

I would like to see some progress spinner. Also I would rely upon it in tests in that specific case checking the balance

### Screenshot (if appropriate)

https://dashboard.cypress.io/#/projects/1it63b/runs/501/specs
run login.spec video and see after connecting the balance is 0 for the time before test passes

**Comment by slaweet** [comment]
Before the account info is fetched, the account info should not be displayed at all.
