### ISSUE TITLE
MAX button for amount LSK - like lisk nano wallet

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-hub#1412]
Please add a Maximum button for the 'Amount' input box

![image](https://user-images.githubusercontent.com/20902562/47776660-350ce000-dcf3-11e8-974d-05ad087cebc1.png)

**Comment by slaweet** [comment]
Hi @Joo5t, thanks for the feedback. This feature is already in progress in 1.6.0 release https://github.com/LiskHQ/lisk-hub/issues/1234
