### ISSUE TITLE
Move send component steps into one folder 

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1419]
### Current behaviour
The Send components are in three folders:
https://github.com/LiskHQ/lisk-hub/tree/v1.5.0/src/components/send
https://github.com/LiskHQ/lisk-hub/tree/v1.5.0/src/components/sendWritable
https://github.com/LiskHQ/lisk-hub/tree/v1.5.0/src/components/sendReadable
### Expected behaviour
All the steps are in subfolders of the `send`. `sendWritable` is renamed to `form`; `sendReadable` is renamed to `confirm` . Same as in https://github.com/LiskHQ/lisk-hub/tree/v1.5.0/src/components/registerDelegate/steps

```
/src/components/send
/src/components/send/steps/form
/src/components/send/steps/confirm
```

**Comment by osvaldovega** [comment]
Fix in PR #1445
