### ISSUE TITLE
Show the usage tracking switcher in settings always

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1454]
Subtask of https://github.com/LiskHQ/lisk-hub/issues/1102

Show the switcher in settings always with a link to Privacy Policy.

Switcher title should say:
`Send anonymous usage statistics`

And have a subtitle:
`For more information refer to our [Privacy Policy](https://lisk.io/privacy)`

**Comment by osvaldovega** [comment]
Issue implemented in PR #1562
