### ISSUE TITLE
Setup coverage checks for Jest tests

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1464]
Subtask of https://github.com/LiskHQ/lisk-hub/issues/1429

- Set coverage checks for Jest 
https://github.com/LiskHQ/lisk-hub/blob/462079c4c707b330fd79d1a1e3c3a0cfaee624cc/jest.config.js#L221-L228
to what we have in karma.conf:
https://github.com/LiskHQ/lisk-hub/blob/462079c4c707b330fd79d1a1e3c3a0cfaee624cc/karma.conf.js#L44-L84 

- Enable sending coverage report from Jest Jenkins build to Coveralls.
https://github.com/LiskHQ/lisk-hub/blob/462079c4c707b330fd79d1a1e3c3a0cfaee624cc/Jenkinsfile#L87-L91

This is blocked by most of the subtasks of https://github.com/LiskHQ/lisk-hub/issues/1429

**Comment by osvaldovega** [comment]
Issues fixed in PR #1507
