### ISSUE TITLE
Refactor votingListView components

### ISSUE THREAD

**Issue by osvaldovega** [LiskHQ/lisk-hub#1470]
Under **src/votingListView** folder there are several components but there are 4 in total, that looks like duplicated.

At this point, the component **delegateList** and **voteList** are components that display a list of data (delegates) and the only difference is that in the **delegateList** you can see an checkbox element where you can select (vote) and in the **voteList** you can see the same type of data but without the checkbox.

Both components use another component for render the list of delegates and those are **delegateRow** and **voteRow**, these elements are duplicated as their functions is the same wit a few differences as I already mentioned.

- Check and review the data the both components display.

- Normalize the data to display.

- Remove delegateRow and voteRow and use one component for render the normalized data/

**Comment by slaweet** [comment]
Cleaning up - Closing issues that were open for a long time without any update. We can re-open if needed. This should be solved when implementing the new delegates
