### ISSUE TITLE
Implement bright and monochrome background

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1494]
Subtask of https://github.com/LiskHQ/lisk-hub/issues/1233
It should look like this:
<img width="1383" alt="screen shot 2018-11-16 at 13 36 52" src="https://user-images.githubusercontent.com/1254342/48621729-b7a8c700-e9a4-11e8-97b0-2378325b62c5.png">

https://taikonauten.invisionapp.com/d/main/#/console/15987783/331771153/preview

**Comment by osvaldovega** [comment]
Issue fixed in PR #1514
