### ISSUE TITLE
Remove "Transfer" module from wallet and add buttons "Send" and "Request"

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1497]
Subtask of #1466 

The goal of this ticket is to remove "Transfer" module from wallet and add buttons "Send" and "Request" that link to pages created in https://github.com/LiskHQ/lisk-hub/issues/1495 and https://github.com/LiskHQ/lisk-hub/issues/1493. Therefore those two should be done first.

**Comment by osvaldovega** [comment]
issue fixed in PR #1540
