### ISSUE TITLE
Fix wallet.js test file to can be test it by Jest

### ISSUE THREAD

**Issue by osvaldovega** [LiskHQ/lisk-hub#1500]
The **test/integration/wallet.js** file right now is skip it, because is thrown some random errors.

### Steps to reproduce

1. check the 'test/integration/wallet.js' file and remove the skip word from the it test.
2. run the command npm run test-jest. 
1. The error message should be making reference to **_retries** property.

### Actual result

```
 FAIL  test/integration/wallet.test.js (50.297s)
  ● @integration: Wallet › Send › Scenario: should allow to send LSK from unlocked account with second passphrase › And I click "send next button"

    TypeError: Cannot read property '_retries' of undefined

      at markRemainingTestsAndSubSuitesAsPending (node_modules/mocha-steps/lib/step.js:3:22)
      at Object.sync (node_modules/mocha-steps/lib/step.js:39:7)
```

### Expected result

The test/integration/wallet.js could be tested without skip any test

**Comment by Efefefef** [comment]
Closing due to the fact I'm removing this integration test as a partial duplicating of e2e test
