### ISSUE TITLE
Request: Sum in detailed request mailto link is not specified

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1550]
### Steps to reproduce

1. Request specific amount
1. Click the link and check the content

### Actual result

Sum in subject and body is not there
![image](https://user-images.githubusercontent.com/6704159/49651337-28388600-fa2f-11e8-9aae-8384e077af74.png)

### Expected result

![image](https://user-images.githubusercontent.com/6704159/49651340-2a9ae000-fa2f-11e8-912f-4915104dcb76.png)

### Version

1.8

**Comment by osvaldovega** [comment]
issue closed on PR #1554
