### ISSUE TITLE
Request: Okay is disabled unless you have entered amount

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1551]
### Steps to reproduce

1. Request specific amount
1. Click ok

### Actual result

It is disabled. I cant simply skip this screen

### Expected result

Ok button is enabled

### Version

1.8

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/49651609-f7a51c00-fa2f-11e8-9b8e-4920aa675c8f.png)

**Comment by osvaldovega** [comment]
issue closed on PR #1554
