### ISSUE TITLE
Request: Cant start the app with the /wallet/request link

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1552]
### Steps to reproduce

1. Close the app
1. Enter http://localhost:8080/#/wallet/request

### Actual result

An error occoured while rendering this page

### Expected result

Request page is rendered

### Version

1.8

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/49651735-52d70e80-fa30-11e8-8345-e26ccfffeaae.png)

**Comment by osvaldovega** [comment]
issue closed on PR #1554
