### ISSUE TITLE
Initialization: Buttons are not well aligned

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1553]
### Steps to reproduce

1. Login as ready for initialization account `traffic woman skull forest nerve luggage traffic wrestle ensure organ moon century`
1. Go to wallet
1. Click send

### Actual result
Button vertical alignment is a bit different (check  screenshots), it should be uniformal
Text on confirm button is not centrally aligned
'Confirmation in the next step' text is to close to the border
next button is abnormally big :)

![image](https://user-images.githubusercontent.com/6704159/49651937-dabd1880-fa30-11e8-9209-0785e62228e8.png)
![image](https://user-images.githubusercontent.com/6704159/49651964-ed375200-fa30-11e8-8c0c-6b1773805837.png)

**Comment by osvaldovega** [comment]
issue closed on PR #1554
