### ISSUE TITLE
"No results found" after finding results

### ISSUE THREAD

**Issue by Korben3** [LiskHQ/lisk-hub#1568]
After a successful search, clicking in the search field again results in a "No results found" message.

### Steps to reproduce

1.  Open lisk hub
2. Search for korben3.
3. Correct results appear.
4. Click in the search input field and press enter again, without changing or removing the current value. 
5. Page shows "No results".

### Actual result
No results.

### Expected result
Show found search results.

### Version
1.7.0

### Screenshot (if appropriate)
![image](https://user-images.githubusercontent.com/42899281/49900501-0b50e800-fe5f-11e8-91b1-5d48682ad900.png)

**Comment by Korben3** [comment]
In addition the text "No results Search for Lisk ID or Transaction ID" should be "No results Search for **Delegate**, Lisk ID or Transaction ID"

**Comment by slaweet** [comment]
@Korben3 Thank you for the report

@Efefefef the condition should be adjusted here: https://github.com/LiskHQ/lisk-hub/blob/4e4330a5885facd344924f782ba5c4a4e989e30c/src/components/autoSuggest/index.js#L347-L351
