### ISSUE TITLE
Align look of the dashboard in M breakpoint with L

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1573]
Subtask of #1467

Goals:
- Align look of the dashboard in M breakpoint with L
https://taikonauten.invisionapp.com/d/main/#/console/15987783/336075026/preview
<img width="755" alt="screen shot 2018-12-13 at 11 08 21" src="https://user-images.githubusercontent.com/1254342/49931561-6e766500-fec7-11e8-9091-4a794b6aeb21.png">

**Comment by osvaldovega** [comment]
Issue fixed in PR #1630
