### ISSUE TITLE
Send process inputs labels have wrong styles

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1598]
### Steps to reproduce

1. Open Hub
1. Go to "Wallet"
1. Go to "Send

### Actual result

All input labels are blue and don't have the correct font-size and weight

### Expected result

Input labels should be blue only when focused and have styles like on other pages (e.g. request)

### Version

1.8.0

### Screenshot (if appropriate)

![screen shot 2018-12-14 at 11 38 13](https://user-images.githubusercontent.com/1254342/49998594-faa28e00-ff94-11e8-9b8f-abd0b34a3831.png)

**Comment by osvaldovega** [comment]
Issue fixed in PR #1601
