### ISSUE TITLE
Check for updates breaks the help menu

### ISSUE THREAD

**Issue by cade88** [LiskHQ/lisk-hub#1612]
### Steps to reproduce

1. Open lisk hub
1.  Help -> Check for updates
1. Do not click on "OK" in the message box and instead click on any menu tab like Help again

### Actual result

An empty box appears

### Expected result

Should not be able to click on any menu if the update message box is not closed

### Screenshot (if appropriate)

![capture](https://user-images.githubusercontent.com/42892424/50264132-4915b980-03e7-11e9-9a9d-bbf210180afc.PNG)

**Comment by Efefefef** [comment]
@cade88 this glitch is happening on Electron side. Unfortunately, we can't fix that. But thanks for the report!
