### ISSUE TITLE
Design UI of filters popup in Wallet

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1632]
The goal of this ticket is to design UI based on this wireframe:
https://netguru.invisionapp.com/share/Z8PMN063CNV#/screens/337034069

**Comment by dmrkv** [comment]
1400px:
https://netguru.invisionapp.com/share/6JQ1S6AZR7N
(5 screens)

768px:
https://netguru.invisionapp.com/share/D6Q33OBCZR9
