### ISSUE TITLE
Design UI of filer tags in Wallet

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1633]
The goal of this ticket is to design UI based on this wireframe:
https://netguru.invisionapp.com/share/KRPIHEW6UGC#/screens/335748592_2-2-1_Wallet_Delegate_-_Filters_Results

**Comment by dmrkv** [comment]
1400px
https://netguru.invisionapp.com/share/74Q35SK5MJY
(use ←→, 2 screens)

**Comment by dmrkv** [comment]
768px
https://netguru.invisionapp.com/share/9BQ35TBMQXK

What to do with tags panel:
1. Filtered results: 32 → 32
2. All tags → short to first N symbols
3. It's OK to hide «Clear all filters» button, if there is no space

**Comment by dmrkv** [comment]
Need to be done:
Another version for S Breakpoint with 2 strings

**Comment by sansus** [comment]
L Size - https://netguru.invisionapp.com/share/NAQ7YGSBKRJ
S Size - https://netguru.invisionapp.com/share/UPQ7YBU2S5N
