### ISSUE TITLE
Design UI of balance graph in Wallet

### ISSUE THREAD

**Issue by dmrkv** [LiskHQ/lisk-hub#1638]
UX wireframe:
https://netguru.invisionapp.com/share/Z8PMN063CNV#/screens/337034066

UI with hover-effect:
https://netguru.invisionapp.com/share/HGOHX8L6U3M#/screens/336327393

**Comment by sansus** [comment]
L Size - https://netguru.invisionapp.com/share/VFQ785GH9RE
S Size - https://netguru.invisionapp.com/share/XVQ786456FN

(use arrows to navigate between different states)
