### ISSUE TITLE
Implement the new bottom bar

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1646]
Subtask of #1645 
The goal is to implement this bar:
![screen shot 2019-01-10 at 11 01 08](https://user-images.githubusercontent.com/1254342/50961057-20a14c80-14c7-11e9-9baf-7c66190435ce.png)

https://netguru.invisionapp.com/share/X9PMLKSUNYE#/screens/339318625

**Comment by osvaldovega** [comment]
Issue implemented in PR #1661
