### ISSUE TITLE
Implement the new menu avatar dropdown

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1647]
Subtask of #1645
The goal is to implement this dropdown:
![screen shot 2019-01-10 at 11 04 53](https://user-images.githubusercontent.com/1254342/50961295-9b6a6780-14c7-11e9-8dff-3a683eb2e610.png)

https://netguru.invisionapp.com/share/X9PMLKSUNYE#/screens/339318625

**Comment by osvaldovega** [comment]
issue fixed in PR #1674
