### ISSUE TITLE
Implement the new top bar and remove the sidebar

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1648]
Subtask of #1645
The goal is to implement this top bar:
![screen shot 2019-01-10 at 11 08 40](https://user-images.githubusercontent.com/1254342/50961488-1f245400-14c8-11e9-817d-9d435fbdebe5.png)
https://netguru.invisionapp.com/share/X9PMLKSUNYE#/screens/339319711

## Specification
- Menu items should go to pages as they do in sidebar
- "Delegates" menu item should be displayed only if enabled in settings
- "Sidechains" page should be removed from the menu and from the code
- Account address should have the copy icon next to it and work as before
- The avatar should on click show dropdown menu implemented in https://github.com/liskhq/lisk-hub/issues/1647
- The search bar should work with suggestions as before (maybe look of it can be slightly adjusted to the new colors in no more than 30mins)

**Comment by osvaldovega** [comment]
issue fixed in PR #1674
