### ISSUE TITLE
Implement the style adjustments on the dashboard

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1649]
Subtask of #1645
The goal is to implement the update look of this:
![screen shot 2019-01-10 at 11 10 27](https://user-images.githubusercontent.com/1254342/50961600-6a3e6700-14c8-11e9-8f37-468ac7fe2182.png)

https://netguru.invisionapp.com/share/X9PMLKSUNYE#/screens/339573591

**Comment by osvaldovega** [comment]
Issue implemented on PR #1702
