### ISSUE TITLE
Wallet - Send LSK

### ISSUE THREAD

**Issue by sansus** [LiskHQ/lisk-hub#1691]
### Story: As a user I’d like to send LSK tokens to other users

**1.** We’d like to give users possibility to send their LSK tokens to other users. 

To do so users need to provide following information:
- Recipient (Public address or a name in case of a followed account)
- Amount of the transaction (in LSK)
- Message (optional)

**Designs: [1366px](https://netguru.invisionapp.com/share/7RQ7UWB96MQ
), 768px**

**2.** Upon providing a valid recipient we should show the avatar of a given wallet and a checkmark validating the correct address. The validation happens after user moves to another input or leaves the current one.

**Designs: 1366px, 768px**

**3.** If the recipient address is not correct we should display “Provide a correct wallet address or a name of a followed account” error. The validation happens after user moves to another input or leaves the current one.

**Designs: 1366px, 768px**

**4.** Upon providing a valid amount in LSK we should show its value in other currency (can be defined by the user in settings) and a checkmark validating the correct amount. The validation happens after user moves to another input or leaves the current one.

**Designs: 1366px, 768px**

**5.** If the transaction amount is not correct we should display:

- If the amount is not correct-  “Provide a correct amount of LSK” error.
- If the amount is higher than the (current balance - transaction fee) - "The provided amount is higher than your LSK balance"

The validation happens after user moves to another input or leaves the current one.

**Designs: 1366px, 768px**

**6.** The optional message can have up to 64 characters with a counter showing how many characters are still left.

**Designs: 1366px, 768px**

**7.** Upon providing a correct optional message we should show a checkmark validating a correct message. The validation happens after user moves to another input or leaves the current one.

**Designs: 1366px, 768px**

**8.** If user provides more than 64 characters we should display “-[amount] characters left” in the counter and change the input state to error one.

**Designs: 1366px, 768px**

**9.** Upon clicking “Go to confirmation” we should display a transaction summary showcasing:

- Amount of transaction
- Recipient
- Optional message
- Transaction fee

**Designs: 1366px, 768px**

**10.** Users should be able to  edit all the above details by going to the previous screen using the “Edit transaction” screen.

**Designs: 1366px, 768px**

**11.** If the user has a 2nd passphrase enabled he should provide it to be able to make the transaction.

**Designs: 1366x, 768px**

**12.** Upon clicking “Send [amount] LSK” the transaction is submitted and user should see a transaction submission screen.

**Designs: 1366x, 768px**

**13.** Upon clicking “Back to Wallet” user should be redirected to his wallet

**Comment by michaeltomasik** [comment]
- Transfer View 8
---- bookmark design
--- validation changes
- Summary View 3
- Transaction Submitted View 3
