### ISSUE TITLE
Design Request LSK - QR Code

### ISSUE THREAD

**Issue by sansus** [LiskHQ/lisk-hub#1704]
Design a way for users to be able to use a generated QR Code when requesting LSK. The QR code is meant to be used by the Lisk Mobile app.

**Comment by dmrkv** [comment]
Request scenario:
https://netguru.invisionapp.com/share/S6QE1CGN79V
(8 screens, use ←→ keys)

Request, steps with QR code:
https://netguru.invisionapp.com/share/HZQE1CXTQY2
(2 screens, use ←→ keys)

Request S-Breakpoint
https://netguru.invisionapp.com/share/R7QE1BT9JK6
(2 screens, use ←→ keys)
