### ISSUE TITLE
Ledger

### ISSUE THREAD

**Issue by Illuciferium** [LiskHQ/lisk-hub#1719]
### Steps to reproduce

1. https://www.lisktools.eu/liskplay/ and open up Hub with external link
1. send 1 LSK for contest
1. Hub stalls, or infinite looping of Lisk Logo with colors, implying 'loading'
1. Must exit Hub and restart for further operation

### Actual result

id doesn't bring me back to my wallet, Hub becomes inactive 

### Expected result

It should bring me right back to the Hub wallet, and potentially open up the Lisk Block Explore in the browser. It would be nice to see number of conformations added to the 'loading Lisk logo.

### Version

Version 1.10.0-beta.1 (1.10.0-beta.1)

### Screenshot (if appropriate)

-

**Comment by Efefefef** [comment]
Fixed in #1719
