### ISSUE TITLE
Other Wallet - Follow account

### ISSUE THREAD

**Issue by sansus** [LiskHQ/lisk-hub#1723]
### Story: As a user I’d like to follow a regular account

We’d like to give users a possibility to follow non-delegate accounts in order to get notified about their activity.

**1.** Upon clicking “Follow Account” button we should display a tooltip asking users to provide a custom account name. The account name can have up to 20 characters with a counter showing how many characters are still left. 

**Designs:** 

**2.** If the name is not correct we should display “Please provide a correct account name” error.

**Designs:** 

**3.** Users should be able to choose which notifications they’d like to recieve. The options include:

- Showing activity of a given account on dashboard
- Receiving notifications about wallet activity of a given account in notification centre

**Designs:** 

**4.** Upon clicking “Confirm” the tooltip should disappear and the copy inside the “Follow Account” should change to “[checkmark] Following [down arrow]”. Also, the account name should change to custom name provided by the user and a “Followed Account” label should be display next to account name.

**Designs:** 

**5.** Upon clicking “Following” CTA users should be able to edit the following settings including the name and notification preferences. They can also choose to unfollow account.

**Designs:** 

**6.** When the account is unfollowed the tooltip should disappear and all the elements should go back to the pre-following state.

**Designs:**

**Comment by dmrkv** [comment]
I think it is all just one task, because it is all about one pop-up with different statements.

**Comment by slaweet** [comment]
Implementation is done inside other epics in https://github.com/LiskHQ/lisk-hub/issues/1805 and https://github.com/LiskHQ/lisk-hub/issues/1806
