### ISSUE TITLE
Other Wallet - Follow recipient

### ISSUE THREAD

**Issue by sansus** [LiskHQ/lisk-hub#1725]
### Story: As a user I'd like to be able to follow the recipient of my transaction

We'd like to give users a possibility to follow recipients of their transactions.

**1.** If the user is not already following the recipient of a given transaction we should display "Follow recipient" button on the "Transaction Submitted" screen.

**Designs:** 

**2.** The button should behave the same way as the buttons described in the https://github.com/LiskHQ/lisk-hub/issues/1723 and https://github.com/LiskHQ/lisk-hub/issues/1724 epics.

**Designs:** 

**3.** If the user is already following the recipient the "Follow recipient" there is no need for such button and it should not be visible.

**Designs:**

**Comment by slaweet** [comment]
To be implemented in the Send LSK epic with this ticket https://github.com/LiskHQ/lisk-hub/issues/1806
