### ISSUE TITLE
Other Wallet - Send LSK to this Wallet

### ISSUE THREAD

**Issue by sansus** [LiskHQ/lisk-hub#1726]
### Story: As a user I’d like to send LSK tokens to a given account

We’d like to give users possibility to send their LSK tokens to a given wallet.

**1.** The LSK sending should work exactly the same as in https://github.com/LiskHQ/lisk-hub/issues/1691 but with already pre-filled recipient.

**Designs:**

**Comment by slaweet** [comment]
Implemented in https://github.com/LiskHQ/lisk-hub/issues/1777
