### ISSUE TITLE
Design a pop-up with Terms of use

### ISSUE THREAD

**Issue by dmrkv** [LiskHQ/lisk-hub#1732]
Users must see a pop-up with link to Terms of use (like in every website)

***

List of legal requirements:
(cases)
1. to the people that already have lisk hub installed - by e.g. pop-up window with an information that the terms of use were updated and they may be read here...
2. to new users, probably during the installation process, when they are provided with the content of the terms of use and where they need to agree on them (like in these installation processes where nobody realy reads terms and coditions but just clicks ok
3. current terms of use must be available for users to be accessed from the application layer, maybe in settings menu - Marcin Zarakowski does not know how does it function at this moment

Marcin Zarakowski talked to Ali, who mentioned that it might be reasonable to refer there  to lisk.io website with terms of use uploaded  - e.g. https://lisk.io/terms-conditions (here's still the old version)

**Comment by dmrkv** [comment]
1. Banner for new user:
https://netguru.invisionapp.com/share/WKQF6XZSQT2
Proposition is to show it as a banner instead of show s-th during the installation.

2. banner for updated terms of use:
https://netguru.invisionapp.com/share/JZQF6ZEUQX7

3. About adding link to settings — as far as we don't have designed a new settings page, maybe just add a link near all other links in Settings?

**Comment by dmrkv** [comment]
Updated:
https://netguru.invisionapp.com/share/45QG2QJUHBF

**Comment by dmrkv** [comment]
So we need to create a fullscreen page, when the user run Lisk Hub very first time.
And user can't access Lisk Hub without clear accepting terms of use.

After that, when Terms of Use will be updated, just a banner in the top of every page is enough.

**Comment by dmrkv** [comment]
Updated.
For new user 1st screen right after the installation and before everything else (like login or registering)
https://netguru.invisionapp.com/share/B2QH1O2KMVS

For updated Terms of Use
https://netguru.invisionapp.com/share/HUQH1OWRJKN

**Comment by dmrkv** [comment]
Updated with help Marcin, new copy

New user:
https://netguru.invisionapp.com/d/main#/console/16675939/346386131/preview

Updated Terms of Use:
https://netguru.invisionapp.com/share/45QG2QJUHBF#/346386132_12-2-2-Terms-Of-Use-Alternate-Version

**Comment by dmrkv** [comment]
Here are two options for having link to Terms of Use, made quickly right in HTML ^^

<img width="1718" alt="option_1" src="https://user-images.githubusercontent.com/30055225/52793759-b3a54780-306e-11e9-9a9a-63b12d8d468b.png">
<img width="1439" alt="option_2" src="https://user-images.githubusercontent.com/30055225/52793760-b3a54780-306e-11e9-8ee5-94880be53ae1.png">

**Comment by slaweet** [comment]
Let's go with the link in left column. Ticket good to close.
