### ISSUE TITLE
Lisk Hub does not start anymore on Linux: RangeError, Maximum call stack size exceeded

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-hub#1733]
### Steps to reproduce
1. download lisk-hub-linux-x86_64-1.10.0-rc.1.AppImage
2. make it executable (`chmod +x lisk-hub-linux-x86_64-1.10.0-rc.1.AppImage`)
3. start it (`./lisk-hub-linux-x86_64-1.10.0-rc.1.AppImage`)
4. Popup, say "No", when it asks if it should be integrated into the system. (Problem exists also when I answer "Yes")
5. Error, does not start

### Actual result
Following Error appears in the console (in step 5 above):

```
A JavaScript error occurred in the main process
Uncaught Exception:
RangeError: Maximum call stack size exceeded
```

UI does not open.

### Expected result
No error, starting

### Version
I have 2 Linux machines, one with an older OS and one with a current Linux
#### Old machine:
No error with versions 1.8.0 and earlier
Error with all 1.9.0 (including rcX) and all 1.10.0 (including beta and rc)

#### New machine:
No error with: 1.9.0-rc.2, 1.9.0, 1.10.0-beta.1, 
(But I get the message: "(electron) 'app.makeSingleInstance(cb)' is deprecated. Use 'app.requestSingleInstanceLock() and app.on('second-instance', cb)' instead."
Error with: 1.10.0-rc.1

**Comment by treepi3** [comment]
Any update on this? I'm unable to open the newer appimages on my Manjaro system. I haven't run them in the command line, but when trying to double click the appimage file it will ask me to add it to the menu but it doesn't open.

**Comment by michaeltomasik** [comment]
@treepi3 We will try to solve it this week but It is hard to predict this one. I will keep You updated!
