### ISSUE TITLE
Search for transactions, accounts and delegates

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1749]
Search for transactions tasks:
- Design search dropdown for transaction id search
https://netguru.invisionapp.com/share/9UQFHMWMHCE
- Design transaction detail page — send
https://netguru.invisionapp.com/share/PWQFHN1R9AZ
- Design transaction detail page — vote
https://netguru.invisionapp.com/share/TFQFHN6YJ7A
- Design transaction detail page — 2nd passphrase registration
https://netguru.invisionapp.com/share/FCQFHNB2GJH
- Design transaction detail page — delegate registration
https://netguru.invisionapp.com/share/FCQFHNB2GJH

Lisk account search tasks:
- Design the Votes tab on the account page
  https://netguru.invisionapp.com/share/GVQ8VQM28PX#/screens
- Design search dropdown for Lisk ID search
  https://netguru.invisionapp.com/share/KXPMNR3YVJG#/screens/337039673

Delegate search tasks:
- Design search dropdown for delegate name search
  https://netguru.invisionapp.com/share/GJPMNPEH52P#/screens/337039674
- Design read-only delegates detail page (without newsfeed and extra data like bio, country because backend is not ready)
https://netguru.invisionapp.com/share/XPQFHOADCMG (use ←→ keys)

**Comment by dmrkv** [comment]
- Changed link for transactions search
- added links to transaction details pages

**Comment by dmrkv** [comment]
Remove «Show all results for transaction», because it will be always just one result
