### ISSUE TITLE
Design the Votes tab on the account page

### ISSUE THREAD

**Issue by dmrkv** [LiskHQ/lisk-hub#1754]
* Design the Votes tab on the account page
  https://netguru.invisionapp.com/share/GVQ8VQM28PX#/screens

1. Add tabs to Wallet + don't forget to design it for all old pages
2. Design a table
3. Design a table for small screens

**Comment by dmrkv** [comment]
Updated
https://invis.io/94QNSKY5PVR

**Comment by sansus** [comment]
The L views with filters, empty states and loading states:
https://netguru.invisionapp.com/share/VAQUVID5GUM

The main S view - do we need all the states in S size?
https://netguru.invisionapp.com/share/7WQUWA8UHR2

**Comment by sansus** [comment]
Updated the designs:

- Removed LSK from table headers
- Added the LSK to the amounts to be consistent with the transaction table
- Updated the filter results to showcase that the searched string can be inside of a delegate name
- Added designs for 3 tooltips: Forged, Productivity and Vote weight:

L - https://netguru.invisionapp.com/share/NRQVO14USKQ
S - https://netguru.invisionapp.com/share/7WQUWA8UHR2
