### ISSUE TITLE
Design read-only delegates detail page

### ISSUE THREAD

**Issue by dmrkv** [LiskHQ/lisk-hub#1756]
* Design read-only delegates detail page (without newsfeed and extra data like bio, country because backend is not ready)
  https://netguru.invisionapp.com/share/XPQFHOADCMG (use ←→ keys)

**Comment by dmrkv** [comment]
Design, 1st option
https://invis.io/ESQQQCSKTCY

**Comment by sansus** [comment]
The 1366 and 768 versions:
https://netguru.invisionapp.com/share/GDQUS2ST9BH
