### ISSUE TITLE
Migrate to the new design

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1767]
This epic aims to provide the list of action points we have to take to migrate the entire Lisk Hub to the new branding language.
Pages include: 

 - Dashboard #1936 
 - Main header #1838 
 - Wallet
   - Transaction details
   - Transactions list
   - Other wallets
 - Followed accounts #1994
   - Followed accounts list
   - Add new item
 - Delegates #1926 
   - Delegates list
   - Vote summary
   - Confirmation
   - Register a delegate
 - Votes
 - Settings #1995

**Comment by yasharAyari** [comment]
All of the issues of this epic has been merged.
