### ISSUE TITLE
Usage tracking doesn't work due to double slash in the URL

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1769]
### Steps to reproduce

1. Don't use `Lightcurve` Wi-fi (because that one is white-listed)
1. Go to settings
1. Enable "Anonymous usage statistics"
1. Navigate to some other page

### Actual result

Request to `matomo.lisk.io//piwik.php?...` fails with 403 error, because of the double `//`

The end user won't notice anything is wrong, but we don't get any data. 

### Expected result

Request to `matomo.lisk.io/piwik.php?...` is successfully sent

### Version

1.11.0-beta.1, 1.10.0

### Screenshot (if appropriate)

![screen shot 2019-02-12 at 16 23 01](https://user-images.githubusercontent.com/1254342/52709780-fe02c780-2f8d-11e9-930f-cb924778d37a.png)

**Comment by osvaldovega** [comment]
issue fixed in PR #1771
