### ISSUE TITLE
Implement the new search dropdown in final UI

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1774]
The goal is to implement the new search dropdown and remove the search field in the header. 
After opening the dropdown with the search icon, the input should be focused, interactions should work like with the old design (unless stated below), and the suggestions look like in the new designs: 
1366px: https://netguru.invisionapp.com/share/CSR4TMU85AW#/screens/353544615
768px: https://netguru.invisionapp.com/share/8JR4U4MWF67#/screens/353585930

https://app.zeplin.io/project/5c82526ebf0d81bce46d5255/dashboard?tag=7.0%20Search

### Changes to behavior
- Recent searches are not used/displayed anymore.
- There is a loading bar when an API request to get the results is pending.
- For some search results, different data is displayed than it was in the previous design, according to the designs.

### These parts are to be implemented later:
- "See all results for ..." links in https://netguru.invisionapp.com/share/CSR4TMU85AW#/screens/353544616
- Transactions search by the message (in https://netguru.invisionapp.com/share/CSR4TMU85AW#/screens/353544616)

**Comment by osvaldovega** [comment]
issue implemented on PR #1864
