### ISSUE TITLE
Onboarding: Does not start if settings exist but onboarding is empty 

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1797]
### Steps to reproduce

1. Set localStorage settings: {"areTermsOfUseAccepted":true}
1. Run the app

### Actual result

No onboarding

### Expected result

Onboarding is there is no onBoarding key in settings

**Comment by Efefefef** [comment]
It interferes automated tests

**Comment by michaeltomasik** [comment]
There will be follow up ticket to delete onboarding
