### ISSUE TITLE
Implement send LSK with Ledger in the new design

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1811]
- If hardware wallet is used, the summary step should have the button disabled, and say "Confirm on Ledger"
![screen shot 2019-03-07 at 13 23 44](https://user-images.githubusercontent.com/1254342/53957052-a9aabd80-40dd-11e9-907e-7c3163f01647.png)
- If the transaction is rejected on the device, the error page should be shown, with button to "Retry"
![screen shot 2019-03-07 at 13 37 54](https://user-images.githubusercontent.com/1254342/53957297-479e8800-40de-11e9-86d4-e62ebd54ea7e.png)

**Comment by osvaldovega** [comment]
issue implemented on PR #1814
