### ISSUE TITLE
Prevent accidental search of user's passphrase

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1813]
Currently, a user can paste accidentally passphrase into the search field and it will be used as a search term and sent to a server.

This should be avoided by not making the API request for delegate name if entered search term doesn't match the delegate name regex https://github.com/LiskHQ/lisk-hub/blob/93c9b0a386e47c258ff4ed77a8ad576aa720b0f5/src/components/registerDelegate/steps/choose/choose.js#L22 This will solve the problem because a delegate name doesn't allow spaces and passphrase require spaces, so there is an empty intersection of the two.

BTW the delegate name regex should be defined in this file https://github.com/LiskHQ/lisk-hub/blob/development/src/utils/regex.js and then the regex can be handled same as for Lisk ID and TxID in https://github.com/LiskHQ/lisk-hub/blob/93c9b0a386e47c258ff4ed77a8ad576aa720b0f5/src/utils/api/search.js#L44-L48

**Comment by osvaldovega** [comment]
issue fixed in PR #1864
