### ISSUE TITLE
Migrate top bar to final UI

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1837]
This is a subtask of #1819.

The goal is to update the look according to the designs in
https://netguru.invisionapp.com/share/KGRE2CNVYNT#/screens
https://app.zeplin.io/project/5c82526ebf0d81bce46d5255/screen/5cac3c04d4655b65fd3b98bf

The scope is: 
- top bar (including account dropdown, excluding search dropdown)
- there should be no BTC balance, yet. So far, the LSK address should be kept, including the copy icon. 
- Notifications icon should be skipped for now.

Account dropdown external links should link to:
- Help center: https://lisk.io/help-center
- FAQ's:  Skip for now
- What's new: Skip for now
- Watch tutorials: Skip for now

**Comment by yasharAyari** [comment]
This is a duplicate ticket. the issue has been fixed in #2053
