### ISSUE TITLE
Bookmarks: It is possible to rename delegate's account

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1859]
### Steps to reproduce

1. Open delegate account
1. Bookmark it
1. Go to dashboard
1. Rename bookmarked account
1. Go to the delegate account
1. Click on bookmark button

### Actual result

Bookmark's name is delegate name

### Expected result

It should be new bookmark'd account name
or
We should not be able to rename delegate's names as bookmarks

**Comment by slaweet** [comment]
## Expected result
The user should not be able to rename delegate bookmark on the dashboard - the input should be disabled/read-only when editing. For this, we might need to store the flag that the account is a delegate when following a delegate.

**Comment by Efefefef** [comment]
@slaweet What if it wasn't a delegate at the bookmarking time, was renamed and then registered as a delegate

**Comment by slaweet** [comment]
@Efefefef I consider that situation so much of an edge case that showing either name (delegate or local bookmark) is fine.
If the user is in this unlikely situation and wants to align the names, he can just unfollow and follow again.
