### ISSUE TITLE
Wallet: Since last login number is mistakingly manipulated

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1872]
### Steps to reproduce

I've seen the bug many times, just not so easy to reproduce because I can't see where it happens exactly.
Here is the supporting evidence
1. at 15:42 I checked my delegate's balance 44,058.95447447 
1. I waited for one forging round to happen
1. at 16:08 balance became 44,061.95447447 which is correct

### Actual result

Since last login number is +30.00693156 LSK
localstorage
balance: "4406195447447" 
lastBalance: "4403194754291"

### Expected result

No crazy scientists manipulate numbers
+3 LSK

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/55169709-8a9bca80-5175-11e9-8174-69b0ef8bacfc.png)

**Comment by slaweet** [comment]
Everything is good on Hub, there are some inconsistencies on backend API.
