### ISSUE TITLE
Rerun failed e2e tests with enabled recording

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1940]
### Description of the problem
Since Cypress introduced new Dashboard Plans we need to reduce the number of test recordings to try to fit the cheapest plan possible

### Suggested solution

1. Run all test files without recording
1. Save the log
1. Grep all test files names preceded with ✖ `✖ search.spec.js` from the results table
1. If all is passing notify Github with green and without URL for dashboard run
1. If there are failed tests - run tests again adding `--record` and `--spec` with a list of grepped test files 
https://docs.cypress.io/guides/guides/command-line.html#cypress-run-spec-lt-spec-gt
1. Notify Github with success or failure with the link as it works now

![image](https://user-images.githubusercontent.com/6704159/56293934-b554bf80-6132-11e9-8a71-1c9d5e1207bd.png)

**Comment by Efefefef** [comment]
For the test we need to change the CYPRESS_RECORD_KEY. Because our current 'organisation' ran out of test recording limit for April. I will provide you in PM

**Comment by slaweet** [comment]
I like the idea, @Efefefef. 

If we go for it, we should keep an eye on how many tests are in each file so that we don't rerun too many tests unnecessary. Most are under 10, which is IMO good. Bigger ones (e.g. `wallet.spec.js`) can maybe split to smaller.

**Comment by fchavant** [comment]
There is no such secret stored in Jenkins and I cannot find any usage of `CYPRESS_RECORD_KEY` in the Jenkinsfile either.

**Comment by slaweet** [comment]
@fchavant maybe `CYPRESS_RECORD_KEY` not secret, but just regular env variable. It must be there, otherwise, we wouldn't have any recordings in our cypress dashboard organization.

**Comment by fchavant** [comment]
@slaweet @Efefefef how can I get cypress to run only certain tests?
Passing files as parameter (e.g. `npm run cypress:run -- --record search.spec.js`) does not seem to work.

**Comment by Efefefef** [comment]
@fchavant `npm run cypress:run -- --spec "test/cypress/katze.spec.js,test/cypress/hund.spec.js"`
