### ISSUE TITLE
A Javascript error occurred in the main process

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-hub#1951]
I just updated to the latest Hub version. 
Loggin in went fine. 
Sending a transaction went fine.
Now this showed up but im not sure what the last button was that I pressed. 
Can I provide more information somehow?

![image](https://user-images.githubusercontent.com/20902562/56413868-260df000-6289-11e9-82e7-02657c76c8bb.png)

**Comment by Efefefef** [comment]
@Joo5t This error usually indicates that the connection was dropped. It could have happened while you were attempting to download the new version. Are you sure you have updated and restarted Lisk Hub before getting this error?
Did you get the same mistakes after that?

**Comment by Joo5t** [comment]
Srry for the late reply...too busy @LiskCenter 😀

I cant remember anymore so better close this ticket. I do remember the issue did not got back once I restarted the Hub.

**Comment by Efefefef** [comment]
Ok, @Joo5t thank you for the response. Closing the issue
