### ISSUE TITLE
Create e2e tests for BTC feature

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#1958]
Should test against BTC testnet. Should cover
 - Start send process against testnet.
 - feel a predefined BTC address.
 - Feel a minimum valid amount.
 - Choose low process speed.
 - Confirm the transaction.
 - Click success confirm button. 
 - Check the pending transaction in transactions list.

@Efefefef Feel free to tweak the details of the scenario according to your needs.

**Comment by Efefefef** [comment]
@yasharAyari We should reconsider the test scenario to include only e2e necessary parts.
For sending BTC I propose to go the easy way and use directly testnet. If funds will run out too fast then we can think of bitcoin simnet deployed somewhere and implement support for it in hub.

**Comment by Efefefef** [comment]
Good Idea to run this test only if all others pass - to avoid leaking testnet btc
