### ISSUE TITLE
Ledger not being recognized if connected after lisk-hub is open.

### ISSUE THREAD

**Issue by massao** [LiskHQ/lisk-hub#1976]
### Steps to reproduce

1. Open Lisk-hub.
1. Set LocalStorage item `trezor = true`
1. Connect and unlock Ledger
1. Ledger isn't recognize

### Actual result

After implementing support for Trezor Wallets, Ledger isn't being recognized if it's not unlocked, and inside the lisk app before opening the lisk-hub

### Expected result

Ledger should be able to be unlocked after the lisk-hub application is open.

### Version

1.17

**Comment by Efefefef** [comment]
I changed the tag to bug-unreleased because its only in beta release

**Comment by Efefefef** [comment]
Cant reproduce. Please @massao specify the version if we need to keep this one as a separate ticket or close it with `invalid` label
