### ISSUE TITLE
Can't send tx with Ledger Nano S in Lisk hub 1.16.0

### ISSUE THREAD

**Issue by Lemii** [LiskHQ/lisk-hub#1986]
### Steps to reproduce

1. Connect Nano Ledger S and open Lisk app
1. Open Lisk Hub
1. Sign in with Nano Ledger S
1. Open Account
1. Go to My Wallet
1. Open Send Lisk function (via the button, or any other route)
1. Fill in form and click 'Go to Confirmation'

### Actual result

The following error pops up.

```
Transaction aborted on device
You have cancelled the transaction on your hardware wallet.
```

Nothing happens on the Nano Ledger S.
### Expected result

A confirmation alert should pop up on the Nano Ledger S, asking the user to confirm the TX.

I've since then rolled back to Lisk Hub 1.15.0, and all is working fine there.

### Version

Lisk Hub 1.16.0
Nano Ledger S firmware 1.5.5
W10

**Comment by Efefefef** [comment]
This one was solved in 1.18.0

**Comment by derevyan** [comment]
I have this issue on nano X with firmware Firmware 1.2.4-1

**Comment by tandasima** [comment]
Same here, seeing this today. I am not able to initialize the account.

**Comment by retiedt** [comment]
I have the same problem. I am also not able to initialize the address on my ledger nano s. Lisk app firmware 1.3.1
