### ISSUE TITLE
Initialize Lisk Id: Barely visible Create first tx link 

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#1996]
### Steps to reproduce

1. Login as not initialized account with some balance
1. Check out the initialization banner

### Actual result

Create first tx link is Barely visible 

### Expected result

Text is readable

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/57447471-727c9800-7257-11e9-9094-a13ee049b211.png)

**Comment by Efefefef** [comment]
⚠️ PR was not merged into the development branch

**Comment by slaweet** [comment]
I was checking it in 1.19.0-beta.1 and looks it got merged by now. Feel free to re-open if there's still a problem @Efefefef
