### ISSUE TITLE
Create a generic checkbox component

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2037]
### Description of the problem
Create a checkbox component with 4 states: checked-confirmed, unchecked-confirmed, checked-not-confirmed and unchecked-not-confirmed - design
We need this checkbox in the delegates page, as well as in settings.

This is a prerequisite of #1926

**Comment by slaweet** [comment]
Already done together with new delegates page https://github.com/LiskHQ/lisk-hub/blob/development/src/components/toolbox/checkBox/index.js
