### ISSUE TITLE
Implement My Recent Transactions dashboard module

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2039]
A step to implement the new design of the dashboard page is to adapt My Recent Transactions to the new branding language. 
There are design guides provided for the [empty](https://projects.invisionapp.com/d/main#/console/17570736/364218738/preview) and [full](https://projects.invisionapp.com/d/main#/console/17570736/364218743/preview) states of this component.

The component only shows the latest 5 transactions of the active token. meaning that the title changes according to the active token: Recent Lisk transactions or Recent Bitcoin transactions.
Alsop, in case there's a new transaction, aside from being confirmed or pending, the new transaction pushes the 5th transaction out; keeping the list length always 5.

**Comment by Efefefef** [comment]
> Alsop, in case there's a new transaction, aside from being confirmed or pending, the new transaction pushes the 5th transaction out

@reyraa So tx in Recent transactions should appear as soon as it gets confirmed?

**Comment by reyraa** [comment]
@Efefefef as soon as it's created. This list includes the 5 most recent pending and confirmed transactions.
