### ISSUE TITLE
Issue connecting to Leger Nano S

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2047]
### Description

**Recognition issue after the application is run**
Here I'll try to explain a few issues regarding Leger Nano S integration.
1. Run Lisk Hub.
2. Connect Leger Nano
Here I expect Hub to recognise Leger Nano. but it doesn't. You have to restart Hub to make it recognise.

**Wrong title**
1. After Lisk Hub recognised the Leger Nano S hardware wallet,
2. Click on Leger Nano S

Here I expect to see the name of my hardware wallet, but it says Trezor:
![x1](https://user-images.githubusercontent.com/666685/58097967-dea4b780-7bd8-11e9-9519-af8597524300.jpeg)

**Network error**
In the end after you clicked on any address you'll receive a network error, which doesn't seem to be related to network, since the computer is properly connected to network.
![x2](https://user-images.githubusercontent.com/666685/58097979-e4020200-7bd8-11e9-894b-f0de799faecb.jpeg)

**Comment by Efefefef** [comment]
Well, this is outdated. We've discussed it already. I couldn't reproduce connection issue. In 1.18 title problem is fixed
