### ISSUE TITLE
Implement the required view for voting pre-selection using launch protocol

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2054]
### Description of the problem
If the user launches the application using a launch protocol which directly navigates to the voting page, s/he will see the view which indicates the votes that don't need to change, the ones that need to be voted for and finally the ones that need to be un-voted. 

If the vote needs more than one transactions, this page should indicate the correct corresponding fee.
Beside that, it shows the total number of votes after the this action is done.

**Comment by slaweet** [comment]
This was done as part of https://github.com/LiskHQ/lisk-hub/issues/1926 

If there is something missing, please re-open.
