### ISSUE TITLE
Add package lock file to speedup the build process

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2070]
### Description of the problem
Adding package lock file will help Jenkins to speedup the build process by over 5 minutes due to to the use of caching methods.

We have previously removed this file to prevent conflicts, but since this is a automatically generated file and fixing merge conflicts is as easy as
 - Deleting the lock file.
 - Running npm install.
 - pushing the changed file.
and since this only happens once in a local machine and doesn't block Jenkins, reinstating this file seems reasonable. 

### Motivation
Why Package lock?

- And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages."
- Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
- Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
- To facilitate greater visibility of tree changes through readable source control diffs.

**Comment by slaweet** [comment]
This was done in https://github.com/LiskHQ/lisk-hub/pull/2157
