### ISSUE TITLE
Migrate add to bookmark button to the new design

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-hub#2114]
The goal is to implement add to the bookmark button on the wallet page. The designs are ready in [InVision](https://projects.invisionapp.com/share/6STGFKRXRQM#/screens/384055163).

### Design requirements
- Input field should remain `read-only` unless the field is clicked upon.
- Confirmation button ("Save changes") should appear only when the input value is changed.
- Confirmation button should fade in using a similar animation as feedback text.
- Dialog should close after any action (save, edit, remove).
- Space above and below feedback text should be equal.
- Dropdown external padding should be aligned with design
- Delegates can be bookmarked but without the possibility of editing the bookmark name - their delegate name will stay their bookmark name.

**Comment by colado** [comment]
@imdominic 
![Screenshot 2019-09-13 at 10 10 52](https://user-images.githubusercontent.com/33748103/64847239-dd2b4f00-d60e-11e9-9d59-5768cbb07b3c.png)
