### ISSUE TITLE
Don't press the update button 2 times

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-hub#2131]
![image](https://user-images.githubusercontent.com/20902562/59372479-e3780980-8d47-11e9-8a1f-a1f187f7a278.png)

**Comment by Joo5t** [comment]
Now I pressed OK and relaunched Hub to update again and I get this.. 
![image](https://user-images.githubusercontent.com/20902562/59372575-1de1a680-8d48-11e9-87ec-86a311c56dd9.png)

**Comment by Joo5t** [comment]
3rd time relaunch and update worked

**Comment by reyraa** [comment]
We should disable the update button after clicked.
