### ISSUE TITLE
Retrying failed transfer tx fails

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#2138]
### Steps to reproduce

1. Create transfer tx (Don't confirm yet)
1. Block the request url
1. Send the tx
1. Unblock url
1. Retry

### Actual result

Failure

### Expected result

It works

### Screenshot (if appropriate)

![image](https://user-images.githubusercontent.com/6704159/59504730-dbcd7780-8ea3-11e9-89f8-6d8d32cb1690.png)

**Comment by massao** [comment]
@Efefefef Could you test this one again? I couldn't reproduce, maybe some recent change fixed it already .

**Comment by Efefefef** [comment]
Not reproducible anymore
