### ISSUE TITLE
Align the design of Other's Wallet

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#2165]
There are more. See Invision
https://projects.invisionapp.com/d/main#/console/17570736/365484479/preview

![image](https://user-images.githubusercontent.com/6704159/59905941-c1e1e680-9407-11e9-86db-4b414d01c868.png)

![image](https://user-images.githubusercontent.com/6704159/59906004-e342d280-9407-11e9-9264-6259c2235962.png)

![image](https://user-images.githubusercontent.com/6704159/59906020-ec33a400-9407-11e9-9447-7895f6f107d5.png)

**Comment by slaweet** [comment]
This is IMO duplicate to https://github.com/LiskHQ/lisk-hub/issues/2117
