### ISSUE TITLE
Lisk Hub should always connect

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-hub#2191]
If you choose "Mainnet" or "Testnet" in Lisk Hub it should always connect. In the past days several users claimed that nodes were offline and it gives bad reputation to Lisk and an unprofessional feeling. Lisk Hub should always pick only nodes that are online, so users never see "failed to connect" again. The current "lottery"-system is bad.

**Comment by reyraa** [comment]
This seems to be an issue related to [Lisk Elements](https://github.com/LiskHQ/lisk-sdk/issues).
