### ISSUE TITLE
Fix other wallet account information in header for delegates

### ISSUE THREAD

**Issue by osvaldovega** [LiskHQ/lisk-hub#2220]
### Steps to reproduce

1. Open the app.
2. In the search bar looks for any delegate (name or address). 
3. After the page loads ONLY show the delegate name for genesis_1 and not the correct information for selected delegate.

### Actual result

When you search for a delegate and select any delegate from the suggested list, the wallet for this delegate shows only the first suggested delegate name but not the correct one. 

### Expected result

Display the correct delegates name instead of the first suggested delegate from search list

### Screenshot (if appropriate)

![Screen Shot 2019-07-09 at 09 47 39](https://user-images.githubusercontent.com/11184770/60869093-9e53d400-a22e-11e9-9ed0-58b74a918ec4.png)

**Comment by reyraa** [comment]
Duplicated of #2224
