### ISSUE TITLE
After search for any delegate, information is not properly display in wallet page

### ISSUE THREAD

**Issue by osvaldovega** [LiskHQ/lisk-hub#2224]
### Steps to reproduce

1. Login in the app.
2. Click on the search and search for any delegate account 
3. After the wallet details load, check the wallet header and see that there is no delegate title in header 

### Actual result

After search for any delegate and selected it for see more information in wallet page, in the header of the page you can see the avatar and the address of the account.

### Expected result

Instead of see the Avatar and the address when is checking for a delegate should show avatar and title after search it

### Screenshot (if appropriate)

![Screen Shot 2019-07-09 at 17 42 33](https://user-images.githubusercontent.com/11184770/60903057-f7445c00-a270-11e9-8c0d-2fb8c181b622.png)

**Comment by slaweet** [comment]
I checked and it's not happening anymore in https://ci.lisk.io/test/lisk-hub/development/#/explorer/accounts/6307319849853921018L 

Fixed in one of these refactors: https://github.com/LiskHQ/lisk-hub/pull/2297 https://github.com/LiskHQ/lisk-hub/pull/2258 https://github.com/LiskHQ/lisk-hub/pull/2278
