### ISSUE TITLE
[Create account] on HW wallet sign-in page never used.

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-hub#2241]
### Steps to reproduce

1. Click [Sign in with a hardware wallet] on lisk hub 1.19.0-rc1
2. At this time, [Create account] Link not shown
![case0](https://user-images.githubusercontent.com/14948578/61312558-9bab3d00-a833-11e9-9a22-aea5da95c070.png)
3. Connect Trezor T and input pin 
4. At this time,[Create account]Link shown
![point1](https://user-images.githubusercontent.com/14948578/61312816-24c27400-a834-11e9-9180-929107268e8d.png)
5. Click [Create account]
6. I get an error message and can't create the new account
![point2](https://user-images.githubusercontent.com/14948578/61312952-69e6a600-a834-11e9-8415-7cac0b6b0cb3.png)

### Actual result

[Create account] on HW wallet sign-in page never used.

### Expected result

The account linked to the hardware wallet should be created automatically.
 It seems that I should not create  new account manually.

If the create account button is never used with the HW wallet, 
it should be removed from the screen.
Because there are design changes in planned 1.19 new features

### Version

Lisk Hub 1.19.0-rc1

**Comment by reyraa** [comment]
We should show the 'Create account' link only when there's no uninitialised account. When you connect the hardware wallet initially, it automatically creates an account, so we do not need to show this link in the beginning.

**Comment by hitobb** [comment]
I'm checked with v1.20.0-rc0 whether this issue was fixed or not.
The [Create account] Link appears after entering the PIN,
so it looks like it's not solved.

Please check again how to fix.
Thanks.
