### ISSUE TITLE
Account initialization layout is broken

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#2246]
### Steps to reproduce

1. Log in to uninitialized account, e.g. https://github.com/LiskHQ/lisk-hub/blob/d55eee3fced15bd35afe0354bcdd36686312a3b4/test/constants/accounts.js#L53 on localhost devnet

### Actual result

The two buttons in the dark box are below each other
<img width="1679" alt="Screenshot 2019-07-17 at 12 29 28" src="https://user-images.githubusercontent.com/1254342/61373410-0d1dd680-a89a-11e9-9898-3bd798143c93.png">

### Expected result

The two buttons in the dark box are next to each other

**Comment by reyraa** [comment]
Please refer to this [design file](https://invis.io/46TAA1R8KMX#/380059587_Wallet_-_Account_Initialization_Toaster).

**Comment by reyraa** [comment]
Already implemented.
