### ISSUE TITLE
"Recent Lisk Trading" is not displayed correctly.

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-hub#2253]
### Steps to reproduce

Sign in

### Actual result

Dashboard "Recent Lisk Trading" is not displayed correctly.
![bug_screenshot](https://user-images.githubusercontent.com/44485074/61574830-e3fe7f80-aaff-11e9-9105-4a3502ea5845.png)

number in screen shot 
1. amount layout is broken
2. All displayed addresses are recipient addresses

### Expected result

1. Display without line feed.
ex.) 0.92046708 LSK

2. If received, show sender. 
ex.) Same as Wallet "All Transaction"
![expected_result_2](https://user-images.githubusercontent.com/44485074/61574820-c7fade00-aaff-11e9-8a09-6418a8e838b7.png)
)

### Version

OS: Mac Mojave 10.14.5
Hub: 1.19.0

**Comment by hitobb** [comment]
I reproduced this behavior.

---

### > 1.amount layout is broken

This only happens when the LiskHub window is made smaller. Probably the expected behavior.

### > 2.All displayed addresses are recipient addresses

**I think this behavior is the problem.**

---
I'll organize information and follow up.

**Comment by hitobb** [comment]
### Steps to reproduce

1.  Signin to LiskHub

2. Check [Recent Lisk Transactions]
![1](https://user-images.githubusercontent.com/14948578/63316398-b482a300-c349-11e9-8966-d8fe3fb0b989.png)

![2](https://user-images.githubusercontent.com/14948578/63316472-fa3f6b80-c349-11e9-9bd4-5209080017fd.png)

In this case
```
3235xxxx -160LSK
1623xxxx  160LSK
3235xxxx -240LSK
1623xxxx    1LSK
3235xxxx  -10LSK
```

3. Click [View All]

4. Check [All Transactions] It seems that sender address is mismatched
![3](https://user-images.githubusercontent.com/14948578/63316458-edbb1300-c349-11e9-8ac4-531a707d997d.png)

In this case
```
3235xxxx -160LSK
1645xxxx  160LSK <= this
3235xxxx -240LSK
1350xxxx    1LSK <= this
3235xxxx  -10LSK
```

5. Lisk explorer and [All Transactions] are same.So,[Recent Lisk Transactions] list is mistake.

### Actual result

Lisk explorer, [Recent Lisk Transactions]  and [All Transactions] are same value.

### Expected result

Just sign in.

### Version

LISK Hub: 1.19.1
OS: Windows 10 Home 1903 build 18362.295 Japanese
