### ISSUE TITLE
An error occurs on the BTC wallet page

### ISSUE THREAD

**Issue by lisknonanika** [LiskHQ/lisk-hub#2254]
### Steps to reproduce

1. Select Bitcoin Wallet
![btc_select](https://user-images.githubusercontent.com/44485074/61579500-cf8ea700-ab40-11e9-83f3-62db7fb90fdd.png)

2. Select Wallet
![wallet_select](https://user-images.githubusercontent.com/44485074/61579505-df0df000-ab40-11e9-9fc3-c073322f86c3.png)

**Error log:**
> balanceChart.js:19 Uncaught TypeError: {(intermediate value)(intermediate value)}[(0 , _transactions.getTokenFromAddress)(...)] is not a function
    　at getNormalizedTimestamp (balanceChart.js:19)
    　at Object.getChartDateFormat (balanceChart.js:128)
    　at BalanceGraph.render (balanceChart.js:16)
    　at finishClassComponent (react-dom.development.js:7873)
    　at updateClassComponent (react-dom.development.js:7850)
    　at beginWork (react-dom.development.js:8225)
    　at performUnitOfWork (react-dom.development.js:10224)
    　at workLoop (react-dom.development.js:10288)
    　at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    　at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
getNormalizedTimestamp @ balanceChart.js:19
getChartDateFormat @ balanceChart.js:128
render @ balanceChart.js:16
finishClassComponent @ react-dom.development.js:7873
updateClassComponent @ react-dom.development.js:7850
beginWork @ react-dom.development.js:8225
performUnitOfWork @ react-dom.development.js:10224
workLoop @ react-dom.development.js:10288
callCallback @ react-dom.development.js:542
invokeGuardedCallbackDev @ react-dom.development.js:581
invokeGuardedCallback @ react-dom.development.js:438
renderRoot @ react-dom.development.js:10366
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421
react-dom.development.js:9747 The above error occurred in the <BalanceGraph> component:
    　in BalanceGraph (created by I18n)
    　in I18n (created by Translate(BalanceGraph))
    　in Translate(BalanceGraph) (created by WalletTab)
    　in div (created by WalletTab)
    　in div (created by WalletTab)
    　in WalletTab (created by WalletTransactionsV2)
    　in TabsContainer (created by WalletTransactionsV2)
    　in WalletTransactionsV2 (created by I18n)
    　in I18n (created by Translate(WalletTransactionsV2))
    　in Translate(WalletTransactionsV2) (created by Connect(Translate(WalletTransactionsV2)))
    　in Connect(Translate(WalletTransactionsV2)) (created by Route)
    　in Route (created by withRouter(Connect(Translate(WalletTransactionsV2))))
    　in withRouter(Connect(Translate(WalletTransactionsV2))) (created by TransactionsDashboard)
    　in div (created by TransactionsDashboard)
    　in div (created by TransactionsDashboard)
    　in TransactionsDashboard (created by Connect(TransactionsDashboard))
    　in Connect(TransactionsDashboard) (created by Route)
    　in Route (created by withRouter(Connect(TransactionsDashboard)))
    　in withRouter(Connect(TransactionsDashboard)) (created by Route)
    　in Route (created by CustomRoute)
    　in ErrorBoundary (created by I18n)
    　in I18n (created by Translate(ErrorBoundary))
    　in Translate(ErrorBoundary) (created by CustomRoute)
    　in main (created by CustomRoute)
    　in CustomRoute (created by I18n)
    　in I18n (created by Translate(CustomRoute))
    　in Translate(CustomRoute) (created by Connect(Translate(CustomRoute)))
    　in Connect(Translate(CustomRoute)) (created by Route)
    　in Route (created by withRouter(Connect(Translate(CustomRoute))))
    　in withRouter(Connect(Translate(CustomRoute))) (created by App)
    　in Switch (created by App)
    　in div (created by App)
    　in section (created by App)
    　in main (created by App)
    　in section (created by OfflineWrapper)
    　in OfflineWrapper (created by Connect(OfflineWrapper))
    　in Connect(OfflineWrapper) (created by App)
    　in App (created by Route)
    　in Route (created by withRouter(App))
    　in withRouter(App)
    　in I18nextProvider
    　in Router (created by HashRouter)
    　in HashRouter
    　in Provider
React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
logCapturedError @ react-dom.development.js:9747
captureError @ react-dom.development.js:10540
renderRoot @ react-dom.development.js:10391
performWorkOnRoot @ react-dom.development.js:11014
performWork @ react-dom.development.js:10967
batchedUpdates @ react-dom.development.js:11086
batchedUpdates @ react-dom.development.js:2330
dispatchEvent @ react-dom.development.js:3421

**Contents of parameter "tx" of getNormalizedTimestamp**
> amount: 6739858
confirmations: 18
data: ""
explorerLink: "https://www.blockchain.com/btctest/tx/eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4"
fee: 14598
id: "eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4"
recipientId: "mvcaQMDpXjYbjnkqdaVvkERpou7rTHVEwY"
senderId: "Unparsed Address"
timestamp: 1563621205000
type: 0

**BTC Transaction**
eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4
https://live.blockcypher.com/btc-testnet/tx/eb1460ed580998bdbd685353e50e3fa2270ebcbf4d2ef8ab4006783e7fac13b4/

### Actual result

An error occurs on the Bitcoin Wallet page

### Expected result

The Bitcoin Wallet page should be displayed

### Version

OS: Mac Mojave 10.14.5
Hub: 1.19.0

### Screenshot (if appropriate)

![error](https://user-images.githubusercontent.com/44485074/61579524-0c5a9e00-ab41-11e9-8de3-8e20bb2a5ccd.png)

**Comment by hitobb** [comment]
This issue has been reproduced in my Windows 10 environment.

### Steps to reproduce

1. Sign in LiskHub 1.19.0 as testnet. 

2. Switch to BTC wallet 

3. In this time,BTC wallet page displaied correctly.

4. Getting testnet BTC from following site

https://testnet.coinfaucet.eu/en/

5. An error occurs on the BTC wallet page

This is the same as lisknonanika's report

### Version

 - Lisk Hub 1.19.0
 - Windows 10 Home 1903 build 18362.239

### Other

is problem only occurs when receiving BTC from the segwit address.
It does not fail to receive BTC as it is displayed correctly on LiskMobile.

https://live.blockcypher.com/btc-testnet/tx/4f818b3cbdac782c04c25d353782c006a15d712a8616431c705f9ce1554eeb65

Please check this behavior,
Thanks,
