### ISSUE TITLE
Load more button doesn't work properly for other than signed-in accounts

### ISSUE THREAD

**Issue by przemerr** [LiskHQ/lisk-hub#2267]
### Steps to reproduce

1. Sign in to Lisk Hub
2. Go to Delegates tab
3. Click any of the delegates
4. Scroll down and press Load more

### Actual result
Load more button doesn't load more transaction, instead it repeats last transactions.

### Expected result
Load more button should load more transactions just like with a signed in account

### Version
Lisk Hub 1.19 Windows

**Comment by reyraa** [comment]
@Efefefef Please investigate the e2e test that should catch this problem. Thank you

**Comment by slaweet** [comment]
Done in #2270
