### ISSUE TITLE
Add German translation for desktop

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-hub#2301]
As user; I'd like to be able to see and use my application in German.

### Motivation
Improves usability by making the application easier to use for user with better German knowledge than English. We'll support more languages in the future, we have started with German since it's the biggest mark of Lisk.

### Description
 - Users should be able to change the language of the application to German (Deutsch) in settings page. #2348 
 - Users must see the application in Deutsch if they have selected this language. #2351
 - The tone of voice and terminology of Lisk Hub and Lisk Mobile must be the same in German and English. #2352
 - Amount separator must match the selected locale/language. #2353
 - Dates must be translated in the selected language. #2354

**Comment by reyraa** [comment]
Language selector in the settings page: [InVision app](https://projects.invisionapp.com/d/main#/console/18170373/377173122/preview)
