### ISSUE TITLE
Support Swiss Franc (CHF)

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-hub#2302]
As a user, i want my application (all Lisk GUIs) to support Swiss currency (Swiss Franc CHF) .

### Description
At the moment we only support Euro and USD in Lisk Mobile and Hub. We want to add Swiss franc to this list, enabling users t see the exchange ratio of their transaction values and account balance in one more fiat currency.

### Acceptance criteria
 - Users must be able to select CHF from the list of currencies in settings page.
 ~~- If selected, users must be able to see their balance in CHF.~~
 - If selected, users must be able to see the value of their transaction in CHF (Send page).

**Comment by slaweet** [comment]
I propose we could make the currency list based on the API https://service.lisk.io/api/getPriceTicker so that we don't have to touch frontend code when adding more currencies to the backend.
Currently the supported values are:
```json
{
  "success": true,
  "tickers": {
    "LSK": {
      "BTC": "0.00011359",
      "EUR": 1.0163817379,
      "USD": 1.135593307,
      "RUB": 74.712868344,
      "GBP": 0.934816258562464,
      "JPY": 120.17549384,
      "CNY": 5.023827607188712
    },
    "BTC": {
      "EUR": "8947.81",
      "USD": "9997.3",
      "RUB": "657741.6",
      "GBP": "8229.7408096",
      "JPY": 1057976,
      "CNY": 44227.727856226
    }
  }
}
```

Also, note that some values are strings and some numbers in the JSON. It should be aligned in service.

**Comment by reyraa** [comment]
For the scope of this ticket, we'll refactor the configuration of existing currencies to read from a central unit.
