### ISSUE TITLE
Align app loader animation to design

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#2307]
## Current behaviour
App loading screen (the one before splash screen) was not updated to the latest design
![Screenshot 2019-08-02 at 11 25 23](https://user-images.githubusercontent.com/1254342/62360078-603d8d80-b518-11e9-818c-7e85b87432b7.png)

## Expected behaviour
App loading screen should be updated to the latest design provided by design team. The animation should be something like https://codepen.io/kenchen/pen/tgBiE

**Comment by reyraa** [comment]
The design team have provided an animation aligned with our minimalistic branding language.
Here you can find the initial screens.

We can use [Lotties](https://airbnb.design/lottie/) to run the animation. It requires a JSON output which I'll provide here.

![Loading_Spinner_Full](https://user-images.githubusercontent.com/666685/62472462-01d61080-b79f-11e9-88ea-a3ec05261f3d.gif)

**Comment by slaweet** [comment]
This animation is currently inlined in the html page and is displayed before all the bundles for css and js are loaded. If we want to use Lottie, it means inlining it in the html page. IMO it's too big for that.

I don't think we should use Lottie for this animation, but pure css animations. I was discussing this with @imdominic few days ago.

**Comment by reyraa** [comment]
@slaweet Agreed. This animation is very minimal and we can implement it using CSS.
