### ISSUE TITLE
Amount floating point must match the selected locale/language

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2353]
As user; I should see the floating point must match my language of choice. 

### Acceptance criteria 
 - No thousand separator is required.
 - The digits must be separated by dot (.) in English and comma(,) in German.
 - If the user pastes a value with thousand separator and floating point, the input shows error.
 - The inserted value is assumed to be in the current language of Lisk Hub. hence, if the separator doesn't match the current language, the input shows error. for example, 1.12 is an invalid input if the current language is German.

**Comment by Efefefef** [comment]
@reyraa Should the recently discussed changes be the part of this ticket? 
If so, please, update the story
