### ISSUE TITLE
Refactor Dropdown usage to use DropdownButton where possible

### ISSUE THREAD

**Issue by massao** [LiskHQ/lisk-hub#2360]
Multiple components had the dropdown implemented before the [DropdownButton](https://github.com/LiskHQ/lisk-hub/blob/development/src/components/toolbox/dropdownButton/index.js) was implemented,  so they are handling the toggle of the dropdown individually, they should be replaced with the DropdownButton to be easier to reuse and keep it consistent.

Components using the Dropdown directly:
`git grep /toolbox/dropdown/dropdown`:
```sh
src/components/header/signInHeader/signInHeader.js:import Dropdown from '../../toolbox/dropdown/dropdown';
src/components/send/transactionStatus/transactionStatus.js:import Dropdown from '../../toolbox/dropdown/dropdown';
src/components/topBar/accountMenu/userAccount.js:import Dropdown from '../../toolbox/dropdown/dropdown';
src/components/topBar/topBar.js:import Dropdown from '../toolbox/dropdown/dropdown';
src/components/transactions/filters/dateFieldGroup.js:import Dropdown from '../../toolbox/dropdown/dropdown';
src/components/transactions/filters/filterContainer.js:import Dropdown from '../../toolbox/dropdown/dropdown';
```

**Comment by osvaldovega** [comment]
the src/components/send/transactionStatus/transactionStatus.js file is using the DropdownButton already
