### ISSUE TITLE
Wallet: Votes: Filtering stop working if entered no-result value

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#2371]
### Steps to reproduce

1. Go to Wallet -> Votes 
1. Type something that will not have any filter results in Filter input

### Actual result

Filtering functionality stuck. There is no way to focus on filter input again.

### Expected result

It is possible to edit the filter query

**Comment by massao** [comment]
https://github.com/LiskHQ/lisk-hub/blob/dea1e4aa325725d60c80b2beae0d34d85dae08f8/src/components/votes/votesTab.js#L116
should be:
```js
disabled={mergeVotes && votes.data.length}
```
