### ISSUE TITLE
Docs: About outgoung transactions links lead to lisk.io/documentation

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#2373]
### Steps to reproduce

1. Click links shown on the screenshots
![image](https://user-images.githubusercontent.com/6704159/63349408-a6d61900-c35b-11e9-81a4-a62dc2aae3b1.png)

![image](https://user-images.githubusercontent.com/6704159/63349416-ab9acd00-c35b-11e9-8c9a-e573dd4856ba.png)

### Actual result

https://lisk.io/documentation

### Expected result

Links lead somewhere to the right place

**Comment by osvaldovega** [comment]
I review this ticket with the marketing department and they explain to me, that right now all those links for Help Center doesn't exist anymore, they are working on all of things right now including this, but they don't have a confirmation date for when this information will be available back.

After spoke with Ali he decided to suspend the ticket for now.
