### ISSUE TITLE
Create the normalizer layer in electron to interact with the hardware wallet

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-hub#2382]
In electron is necessary to have a module that manager all the interactions with the HWManager library.

The purpose of this task is to create a file to manage and consume all the functions from the hw manager library and use it when electron runs, then in this file all the communication between react app and hw manager will be happen.

So when the user wants to send a tx for example this file should receive the call or command from react app, and then use the correct function to communicate with the device, then the response or results should be send back to react app.

This file shouldn't have logic only receive commands from react and receive responses from library and send it to react.

All the normalization of the response should be handle in the eHW Manager side not here.

**Comment by sridharmeganathan** [comment]
This story is not needed anymore.
