### ISSUE TITLE
Translate the remaining titles to German

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2421]
### Description
We have already translated most titles and messages to German by #2406 . There are only a few remaining which are not translated and the English copy is displayed instead. You can easily find them in [common.js](https://github.com/LiskHQ/lisk-hub/blob/948f5c93a22c57ed2bd2332c2672eca0eaf38c3b/i18n/locales/de/common.json file.
This ticket is a follow up for #2352 to finish up the translation task.

**Comment by colado** [comment]
The following sentences are still not translated into German:
- You'll find it in your Wallet and it will be confirmed in a matter of minutes.
- Your session was timed out after 10 minutes of no network activity. You may continue to use certain sections of your Lisk Hub or sign back in to access everything.
- Bookmarked
- You’ll see it in Delegates and it will be confirmed in a matter of minutes.
- Become a delegate summary
- Address already bookmarked

**Comment by reyraa** [comment]
> Address already bookmarked
Konto mit Lesezeichen versehen

> Your {{walletModel}} has an old Firmware. Please update it.
Dein Trezor Model One hat eine alte Firmware. Bitte update diese.

> You'll find it in your Wallet and it will be confirmed in a matter of minutes.
Finde es in deiner Wallet und es wird in wenigen Minuten bestätigt.

> Your session was timed out after 10 minutes of no network activity. You may continue to use certain sections of your Lisk Hub or sign back in to access everything.
Address already bookmarked
Deine Sitzung wurde nach 10 Minuten ohne Netzwerkaktivität abgebrochen. Du kannst weiterhin bestimmte Bereiche deines Lisk Hubs nutzen oder dich erneut anmelden, um auf alles zuzugreifen.
