### ISSUE TITLE
[1.21.0-beta.1] Community feed broken layout

### ISSUE THREAD

**Issue by hitobb** [LiskHQ/lisk-hub#2424]
### Expected result

Same as #2401
Please merge fixed source from 1.20.0.
![Community_feed_Broken](https://user-images.githubusercontent.com/14948578/64469855-61478780-d174-11e9-9f24-7874ba4cca68.png)

### Version
1.21.0-beta.1

**Comment by slaweet** [comment]
Fixed in #2428
