### ISSUE TITLE
Implement the list of blocks in a dedicated screen

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2503]
### Description
Ad a user; I'd like to see the list of latest blocks in a dedicated screen.

### Acceptance criteria 
According to [designs](https://projects.invisionapp.com/share/ZRU30GY5NTX#/screens/385494277_Discovery_-_Blocks_Version_2_-with_Filter_And_Tooltip-)
 - If I click on the block ID I should navigate to the block [details page](https://github.com/LiskHQ/lisk-hub/issues/2505).
 -  If I click on the delegate username, I should navigate to its account page.
 - I should be able to load older (more) blocks.
 - The range of existing blocks in the header must update accordingly.

**Comment by slaweet** [comment]
⏲ Changed estimate from 5 to 3 as it was not as much work.
