### ISSUE TITLE
Implement the filters and sorting on the latest blocks

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2504]
### Description
As a user' I'd like to filter the latest blocks based on the block primary properties. In addition, I'd like to be able to sort the blocks based on block height.

### Acceptance criteria 
According to [designs](https://projects.invisionapp.com/share/ZRU30GY5NTX#/screens/385494274_Discovery_-_Blocks_Version_2_-Filters_Open-)
- I should be able to filter the blocks based on:
   - Start date (no later than end date)
   - End date (no earlier than start date)
   - Generated by (delegate username or address)
- I should be able to sort the list based on height.

### Actions points:
- Generalize filter component on transactions list https://github.com/LiskHQ/lisk-hub/issues/2508
- Use the general filter component on the latest blocks page  https://github.com/LiskHQ/lisk-hub/issues/2509

**Comment by slaweet** [comment]
Changing the estimate from 0 to 1, because the sorting was not part of other tickets.

**Comment by slaweet** [comment]
⏲  Changing the estimate from 1 to 2, because the sorting is bigger than I thought.
