### ISSUE TITLE
Generalize filter component on transactions list

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#2508]
We need to make the existing code of the filters generic so it can be used by other screens such as list of latest [blocks](https://github.com/LiskHQ/lisk-hub/issues/2455) and [transactions](https://github.com/LiskHQ/lisk-hub/issues/2456).

**Comment by slaweet** [comment]
⏲ Changed estimate from 3 to 5 as the refactoring was bigger than we thought.
