### ISSUE TITLE
Analyse the required changes for Dark mode

### ISSUE THREAD

**Issue by sridharmeganathan** [LiskHQ/lisk-hub#2516]
- Investigate the possible solutions for implementing multiple theme in Lisk Hub.

**Comment by yasharAyari** [comment]
We've decided to use `css in js` solution to implement multiple theme support in `lisk-hub`. you can find more information about it on the blew document.
https://docs.google.com/document/d/1ZGnHhdAn6MjMVCX6MzAF-hK_nQHb81TZgDjtyZiu4LY/edit?usp=sharing
