### ISSUE TITLE
investigate about automated visual testing solution

### ISSUE THREAD

**Issue by yasharAyari** [LiskHQ/lisk-hub#2520]
### Description of the problem

We need to have some visual tests for toolbox components to make sure that they render in the way our designer requested.
Currently, we don't have any automated visual tests in our application. So, we can't catch visual bugs that may happen in each pull request.  
### Suggested solution
I think we can find some solution based on `react storybook` which helps us to write some visual test scenario for testing our toolbox components;

**Comment by Efefefef** [comment]
- setup the storybook
- create storybook stories for components we want to visual test
- create percy.io account, project
- install, create config and npm script for @percy/storybook
- setup env in jenkins, identify the pipeline order and modify jenkinsfile
- install github integration for commit checks
- set percy's check as required when we are ready
