### ISSUE TITLE
Lisk Chat option in help tab

### ISSUE THREAD

**Issue by michieldespiegelaere** [LiskHQ/lisk-hub#2527]
### Steps to reproduce

1. Click the help tab in Lisk-hub and the Lisk Chat option will be available.

### Actual result
When clicking on the help tab there is an option for Lisk Chat that leads to https://lisk.chat/ which isn't running anymore.

### Expected result
The Lisk Chat option should be change to Lisk discord with the invitation link for the Lisk discord server. https://discord.gg/lisk

### Version
Lisk-hub 1.21.0 / windows 10

### Screenshot (if appropriate)
![image](https://user-images.githubusercontent.com/17978514/66162647-fc763480-e62e-11e9-87c9-8bd5b0ee0aac.png)

**Comment by slaweet** [comment]
Thank you for reporting. Closing as duplicate to https://github.com/LiskHQ/lisk-hub/issues/2483
