### ISSUE TITLE
Update Type field of transaction filters

### ISSUE THREAD

**Issue by colado** [LiskHQ/lisk-hub#2560]
### Description
As a follow-up ticket of #2512 and following [this comment](https://github.com/LiskHQ/lisk-hub/pull/2540#issuecomment-542722443) the Type filter of the monitor transactions needs to be changed into a dropwdown following [the design](https://projects.invisionapp.com/d/main?origin=v7#/console/18539694/389102939/preview).

**Comment by Efefefef** [comment]
Could you also please implement validation and allow only numbers in this field?
