### ISSUE TITLE
HW: Sign message not working with Trezor T

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-hub#2607]
Try to sign a message with Trezor T. I doesn't work. Not if I am already logged in and not if I am logged out and then login. You don't get to the sign-page.

`lisk://sign-message`

**Comment by slaweet** [comment]
We have a ticket for it but didn't get to work on it so far https://github.com/LiskHQ/lisk-hub/issues/1318

It's good to hear what are our users missing 🙂.  Thank you for your feedback, @punkr0ck

**Comment by reyraa** [comment]
Duplicated of #1318
