### ISSUE TITLE
Percy: Disable percy for regular scheduled builds

### ISSUE THREAD

**Issue by Efefefef** [LiskHQ/lisk-hub#2615]
We need to disable Percy for hourly development and similar builds to limit snapshot usage.
10000 snapshots per month are free.

**Comment by fchavant** [comment]
@Efefefef does it mean [`npm run percy`](https://github.com/LiskHQ/lisk-hub/blob/development/Jenkinsfile#L168) should when the `lisk-hub` Jenkins job is triggered by the [lisk-hub-hourly](https://jenkins.lisk.io/job/hourly-builds/job/lisk-hub-hourly/) job?

**Comment by Efefefef** [comment]
@fchavant Yes, exactly 👍

**Comment by fchavant** [comment]
With https://github.com/LiskHQ/lisk-hub/pull/2617 we can set `SKIP_PERCY: true` for [lisk-hub-hourly](https://jenkins.lisk.io/job/hourly-builds/job/lisk-hub-hourly/) and `npm run percy` will be skipped for hourly builds.
