### ISSUE TITLE
Remove hash in urls

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#327]
### Expected behaviour
The URLs should be without `#` sign: http://lisk.io/hub/main/dashboard

In the electron wrapper `#` is used becase it loads `.../index.html`, but it might be worth to switch it to a simple node server inside the electron app.

### Actual behaviour

The URLs currently would be http://lisk.io/hub/#/main/dashboard

**Comment by faival** [comment]
Suspending issue, there's 1 pending test failing, externalLinks.test.js, and there is dev-ops work involved, therefore we can't merge directly this issue.

**Comment by slaweet** [comment]
Not relevant since removing the hosted version. We can re-open in the future if things change.
