### ISSUE TITLE
Implement vote transaction detail

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#372]
### Expected behaviour
Transaction detail should display for vote tx:
- list "Added votes" and "Deleted votes" that displays `address` (not delegate name) and links to account page.

For vote but also other non-send txs:
- show "Type: vote" instead of "Recipient: ..." 
- Change "Value: 0"

Similarly to:
https://testnet-explorer.lisk.io/tx/12972707285006858917

### Actual behaviour
- no list of votes
- recipient is displayed
- values is not displayed

**Comment by ginacontrino** [comment]
New Pr open for this -> #704
