### ISSUE TITLE
Setup a prototype of cross-browser e2e tests

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#428]
### Expected behaviour
Setup a prototype of using https://www.browserstack.com/ and create a follow-up ticket with what needs to be done to make it part of our CI process.

**Comment by michaeltomasik** [comment]
`"Session ID is null. Using WebDriver after calling quit()?"`
Helpful link:
https://stackoverflow.com/questions/41352248/sessionnotfoundexception-session-id-is-null-using-webdriver-after-calling-quit/41353933

**Comment by michaeltomasik** [comment]
> It seems you are using an Async framework. The driver.quit() (or equivalent command) is getting called first and then another selenium command is triggered for same driver instance, which is causing the issue.
> 
> To debug this you can use one of the following approaches:
> 1. Implement logging with timestamps to track commands sent to BrowserStack by your test script.
> 2. Introduce callbacks to ensure all commands/request are served before driver.quit or an equivalent method is triggered.
> 

~BrowserStack Support

**Comment by michaeltomasik** [comment]
Created follow up ticket https://github.com/LiskHQ/lisk-hub/issues/743

**Comment by slaweet** [comment]
Not relevant since removing the hosted version. We can re-open in the future if things change.
