### ISSUE TITLE
UX for Receiving Lisk

### ISSUE THREAD

**Issue by GusRuss89** [LiskHQ/lisk-hub#460]
Sorry for deleting the issue template, this is more general UX feedback. I was told by the help desk to post as an issue, sorry if there's a better channel.

It wasn't immediately obvious to me what my address was. On signup I am only ever presented with my "Lisk ID", it isn't referred to as an address. That would be fine if there was a "Receive" button or panel that explained that my ID _is_ my address, but it seems I just have to figure this out.

I think if we're aiming for mass adoption, this needs to be clearer. Most wallets have a "Receive" button or tab that just brings up the address, sometimes with a QR code. Maybe QR codes are already on the roadmap, but I think even for now just having a "Receive" button that brings up the address is helpful for UX.

**Comment by slaweet** [comment]
Should be solved with https://github.com/LiskHQ/lisk-hub/issues/465
