### ISSUE TITLE
Login not possible with a passphrase with more than 12 words

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk-hub#461]
### Expected behaviour
Minimum passphrase length is 12, but longer phrases should be allowed too

### Actual behaviour
passphrase length is fixed to 12 words

### Steps to reproduce
try to logon with a 15 words bip39 mnemonic code

![image](https://user-images.githubusercontent.com/17945384/36484397-702ef286-1719-11e8-8c39-a33ddc47ac67.png)

**Comment by TheGoldenEye** [comment]
Any comments?

**Comment by TheGoldenEye** [comment]
Almost 9 months later, I would like to ask for the current status.
Today it was announced that Lisk Nano is finally not supported anymore, 
Thus the last official gui-client disappears, who could deal with passphrases with more than 12 words.
It is certainly true that it is not the norm, but I assert that there are certainly other users besides me who have decided for safety reasons for a longer passphrase and now cannot log in anymore.

**Comment by slaweet** [comment]
Login with BIP39 passphrase up to 24 words was recently implemented in https://github.com/LiskHQ/lisk-hub/issues/461 and will be soon released in Lisk Hub 1.12.0.
