### ISSUE TITLE
Need to zoom to see all on Lisk ID

### ISSUE THREAD

**Issue by senikk** [LiskHQ/lisk-hub#464]
### Expected behaviour
To see the text "Your favorite Lisk IDs"

### Actual behaviour
Its hidden on 100% zoom in Chrome on computer with 1920x1080 resolution.

### Steps to reproduce
<img width="630" alt="2018-02-22 09_01_58-lisk hub" src="https://user-images.githubusercontent.com/400752/36526910-34e902b0-17b0-11e8-87de-d55c4d3c55c7.png">

**Comment by slaweet** [comment]
Thank you @senikk for your feedback.
I have trouble to understand this one.

Your computer screen is1920x1080, but your screenshot dimensions are only 1260×888, so (unless Github is resizing it) I assume your window was not maximized. I tried to create a not maximized window of similar dimensions and it looks fine with the default zoom for me:
![screen shot 2018-02-22 at 14 38 36](https://user-images.githubusercontent.com/1254342/36541447-3795d672-17de-11e8-9e8b-fc7bc809be0f.png)

Can you share how some other page looks for you?
