### ISSUE TITLE
Request LSK token

### ISSUE THREAD

**Issue by senikk** [LiskHQ/lisk-hub#465]
### Expected behaviour
"Quickly send LSK token"

### Actual behaviour
"Quickly send and request LSK token"

### Steps to reproduce
<img width="245" alt="request-lisk hub" src="https://user-images.githubusercontent.com/400752/36527058-cda6274e-17b0-11e8-8e15-28104ec72abb.png">

**Comment by slaweet** [comment]
Done through https://github.com/LiskHQ/lisk-hub/issues/772 and https://github.com/LiskHQ/lisk-hub/issues/782
