### ISSUE TITLE
Menu not scrollable

### ISSUE THREAD

**Issue by senikk** [LiskHQ/lisk-hub#467]
### Expected behaviour
Possible to scroll to get to all icons

### Actual behaviour
Only solution now is to use Zoom on Chrome

### Steps to reproduce
<img width="122" alt="scrollable-lisk hub" src="https://user-images.githubusercontent.com/400752/36527567-87e54a1c-17b2-11e8-9163-2753d76d52cc.png">

**Comment by slaweet** [comment]
This is fixed in the to-be-released 0.9.0 version https://ci.lisk.io/test/lisk-hub/0.9.0/#/dashboard
