### ISSUE TITLE
Reveal the newly generated Lisk ID (Account number) only after the passphrase has been verified

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-hub#474]
### Expected behaviour
The newly generated Lisk ID should not been shown before the passphrase has been verified.

### Actual behaviour
Directly after moving the mouse, the new Lisk ID is shown. This is very dangerous, because a (inexperienced) user who generates a new Lisk ID could use this ID (for example to withdraw LSK from an exchange) without showing and verifying the passphrase. That would result in lost LSK because he can't login into his new account because he doesn't know the passphrase.

My suggestion how to fix that: Don't show the new Id on the page "This is your Lisk ID". Show only the avatar. You could make the new ID blurry, so that it is not readable and add a hint that the passphrase must be shown and verified before the Id is revealed.
In the last screen "Perfect! You’re all set." the Id is shown again anyways.

### Steps to reproduce
* Generate a new Lisk ID
* Move the mouse
* Copy the new Id on the screen "This is your Lisk ID", use it on an exchange to withdraw LSK. Don't click "Get passphrase", close the window.
* Access to this account and the LSK in it (sent from the exchange) is lost forever.

**Comment by slaweet** [comment]
We'll go with`1297********L` solution:
![01_get_access_l-get-access-dashboard-3-a-lisk-l](https://user-images.githubusercontent.com/1254342/37356317-f4b31d9e-26e5-11e8-8b41-cff725d7ede7.png)
