### ISSUE TITLE
Convert Lisk Hub to Progressive Web Application (PWA)

### ISSUE THREAD

**Issue by alepop** [LiskHQ/lisk-hub#509]
### Expected behaviour
Update/Tune/Modify **Lisk Hub** configuration/build processes and code to make a **PWA** from **Lisk Hub**. It will allow installing **Lisk Hub** on mobile devices directly from the site and use as an app.

**why:**
Progressive Web Apps take advantage of new technologies to bring the best of mobile sites & native apps to users. 
**pros**:
 - No installation required
 - No application update required
 - Offline use
 - Network connection is secure
 - Quick loading
 - Home screen icon
 - Single codebase for all platforms
 - Code can run in a background process
 - Custom splash screen / address bar matched a brand color

**cons**:
 - More limited hardware access
 - Not all browsers are supported (Works fine on Android devices, But `IOS` will allow using PWA soon)
 - Still a new technology 

### Actual behaviour
**Lisk Hub** is not a PWA

### Steps to reproduce
None

**Comment by alepop** [comment]
@slaweet yes, thanks. I am taking in mind this plugin to working on this feature.

**Comment by slaweet** [comment]
Not relevant since removing the hosted version. We can re-open in the future if things change.
