### ISSUE TITLE
Code-splitting by routes

### ISSUE THREAD

**Issue by alepop** [LiskHQ/lisk-hub#519]
### Expected behaviour
Modify `webpack` config and `react routing` code to allow split finish bundle into the chanks by routes. Webpack will generate separate bundles for each of the route.  And app will lazy loading needed modules by visited route. Example: If we visit transactions tab we don't need to load explorer relative modules and etc.

This will improve load performance, especially for mobile devices. 
This issue relative to #509 

### Actual behaviour
Lisk Hub shipped to a user as a single code bundle.

### Steps to reproduce
Visit Lisk Hub.

**Comment by slaweet** [comment]
Not relevant since removing the hosted version. We can re-open in the future if things change.
