### ISSUE TITLE
Update babel to preset env 

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#539]
### Expected behaviour

We should be using latest features of babel, and align with best practices, babel preset2015 has been deprecated in favor to use environment preset. 

### Actual behaviour

We are using a deprecated version of Babel preset

```
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
```

### Steps to reproduce
- clear node_modules folder
- run npm install
- run `npm run build`
- verify logs showing WARN messages

**Comment by michaeltomasik** [comment]
I cannot reproduce it on my laptop
