### ISSUE TITLE
Implement logout button

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#540]
### Expected behaviour
- There should be a logout button next to the account avatar.
![screen shot 2018-08-16 at 14 41 18](https://user-images.githubusercontent.com/1254342/44209037-7bc25380-a162-11e8-8c24-632377d8aba6.png)

- The button leads to a confirmation screen.
![screen shot 2018-08-15 at 13 45 33](https://user-images.githubusercontent.com/1254342/44146775-8af2de0a-a091-11e8-8b96-071873bdab73.png)
- Clicking the account avatar no longer links to saved accounts 
- Accounts are no longer saved on login, so closing and opening the app leads to login page
- The timeout no longer locks ID, but rather logs use out. First it shows a warning 1 minute before the timeout

![screen shot 2018-08-15 at 13 47 41](https://user-images.githubusercontent.com/1254342/44146853-d11a26d6-a091-11e8-94a2-5f26bcf93c2f.png)
Then on the timeout this screen is shown:
![screen shot 2018-08-15 at 13 46 50](https://user-images.githubusercontent.com/1254342/44146839-c2421678-a091-11e8-9dd5-e00fe562c81d.png)
- The "Auto-Lock" switcher in settings needs to be updated to say "Auto-logout" and work control the logout.

https://taikonauten.atlassian.net/browse/L20-411

### Actual behaviour
There is no logout button

**Comment by Efefefef** [comment]
Thank you for the description
