### ISSUE TITLE
Show the version number of Lisk Hub somewhere

### ISSUE THREAD

**Issue by simonmorgenthaler** [LiskHQ/lisk-hub#563]
### Expected behaviour
Somewhere (it can be "hidden" in a submenu) the version info of Lisk Hub (offline and online version) should be visible. It helps to track down issues and features. It's difficult to help or use it efficiently if you don't know which version is being used.

### Actual behaviour
As far as I know, the version info is not shown. Correct me if I'm wrong.

### Steps to reproduce
Try to figure out which version you're using.

**Comment by slaweet** [comment]
Good point, we were also facing this problem when deploying new versions, so starting with next version (0.3.0) there will be the version at least in the HTML:
https://github.com/LiskHQ/lisk-hub/blob/689a115cdc9d4f98d140a44df471bd1e7203059d/src/index.html#L5

But I see that it is not the final solution.

However, this is only a problem of the web version. With the web version, it should be clear which version is used based on the date it was used, so I see this as low priority. The desktop version has the version number in "About" dialog.

**Comment by slaweet** [comment]
Not relevant since removing the hosted version. The desktop Hub displays version in "About" dialog. We can re-open in the future if things change.
