### ISSUE TITLE
Create 404 page for all routes

### ISSUE THREAD

**Issue by ginacontrino** [LiskHQ/lisk-hub#584]
### Expected behaviour
To see a 404 page for all broken routes

### Actual behaviour
Currently, the broken explorer routes are not caught:
<img width="1671" alt="screen shot 2018-03-21 at 13 07 58" src="https://user-images.githubusercontent.com/9592216/37709020-20805f30-2d09-11e8-90ea-eb5c7a221c7d.png">

### Steps to reproduce
- Go to e.g. http://localhost:8080/#/explorer/transa

**Comment by michaeltomasik** [comment]
Done in https://github.com/LiskHQ/lisk-hub/pull/625
