### ISSUE TITLE
Move route definitions from app component to constants/routes.js

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk-hub#585]
### Expected behaviour
Routes should be defined in https://github.com/LiskHQ/lisk-hub/blob/development/src/constants/routes.js 
```

export default {
  dashboard: { 
    path: '/main/dashboard',
    component: Dashboard,
    isPrivate: true,
  },
  ...
```
And `app` component should just loop over it, something like:
```
<Switch>
{Object.keys(routes).map(key => (
  <{routes[key].isPrivate ? PrivateRoutes : Route}  render={ ({ match }) => (
     <main className={routes[key].isPrivate ? offlineStyle.disableWhenOffline : null}>
      <Route path={routes[key].path}} component={routes[key].Component} />
    </main>
   )} />
)}
<Switch>
```

https://github.com/LiskHQ/lisk-hub/issues/584 can be solved in here too

### Actual behaviour
App component lists all routes
https://github.com/LiskHQ/lisk-hub/blob/1d734bdb0cd669696d56726a9dd206570226c863/src/components/app/index.js#L40-L65

**Comment by michaeltomasik** [comment]
Done in https://github.com/LiskHQ/lisk-hub/pull/625
