### ISSUE TITLE
Remove "back to lisk.io" from login page

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#599]
# Expected Behaviour
- There should not be a link giving the impression of a back button in login page (user might have come from lisk.io or by direct hit, or in electron app).

To avoid confusion for the user, let's rename the link to "Go to lisk.io", and change the orientation of the arrow to indicate a forwarding action instead of a back action. 

# Actual Behaviour
- User can find a link with the look and feel of a back button.

**Comment by itssujan** [comment]
@faival I went ahead with this small fix as its my first contribution to this project. I later realized that its assigned to you. Hope I didn't step on your toes...

**Comment by michaeltomasik** [comment]
@itssujan Thank you for contributing 😄 We will be adding `good first issue` label on tasks that We think will be good for people that want to start contributing 🖥

**Comment by itssujan** [comment]
@michaeltomasik that's cool...Look forward to being a regular contributor to Lisk...

**Comment by faival** [comment]
@itssujan please review requirement changes to this issue, thanks.

**Comment by itssujan** [comment]
@faival cool..i'll make the changes and open a PR

**Comment by itssujan** [comment]
@faival Would this be good?

![screen shot 2018-03-27 at 11 35 46 am](https://user-images.githubusercontent.com/15159118/37978026-0a00f5fe-31b3-11e8-9325-6a08e711416e.png)
