### ISSUE TITLE
Investigate possible improvements to build time.

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#601]
### Expected behaviour
We should try to decrease build time of a production, dev, and test build goals. 

* Possible bottleneck scenarios: 
- webpack version
- webpack config merges/handlings
- moving of assets
- babel version
- output of logs

Related:
- https://github.com/facebook/jest/issues/2098
- https://github.com/facebook/jest/issues/6766
- https://github.com/jsdom/jsdom/issues/2304
- https://github.com/facebook/jest/issues/6798
- https://github.com/facebook/jest/issues/6769

Examples:
- https://github.com/keyanzhang/jest-css-modules-example/blob/master/package.json
- https://github.com/i18next/react-i18next/blob/23119de14e3f33c6f3c29d6657ad8a0cd7db4c6c/example/test-jest/README.md
### Actual behaviour
Prod, dev, and test goals should take a reasonable time

**Comment by faival** [comment]
Related to #526

**Comment by slaweet** [comment]
Cleaning up - Closing issues that were open for a long time without any update. We can re-open if needed.
