### ISSUE TITLE
CPU load too high after 30 seconds

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk-hub#613]
On Ubuntu 17.10, the Lisk Hub client (AppImage) consumes a lot of CPU power.

My system runs at about 10% CPU when all other UI applications are closed. During Lisk Hub boot, the load jumps to 80 % CPU for less then 10 seconds, which is okay I think. After that there is 30 seconds of peace (~15 % CPU) but then the load goes up and stays at 70 % for as long as Lisk Hub is running.

Is this behaviour expected?

-----------

Tested Lisk Hub versions:

* stable lisk-hub-0.2.0-x86_64.AppImage 
* testing lisk-hub-0.3.0-rc.2-x86_64.AppImage

![load_lisk-hub-0 2 0-x86_64 appimage](https://user-images.githubusercontent.com/2603011/37906816-8883efea-3103-11e8-9139-fae923d47820.png)

![load_lisk-hub-0 3 0-rc 2-x86_64 appimage](https://user-images.githubusercontent.com/2603011/37906822-8de7bfde-3103-11e8-99a6-d60e89a33f7e.png)

System:
Ubuntu 17.10 (64 bit)
Intel® Core™ i5-5300U CPU @ 2.30GHz × 4

**Comment by webmaster128** [comment]
I can reproduce the same pattern with lisk-hub-0.4.0-rc.1-x86_64.AppImage

**Comment by webmaster128** [comment]
![bildschirmfoto von 2018-04-02 01-50-19](https://user-images.githubusercontent.com/2603011/38178690-3edb9b9e-3618-11e8-9a42-c2f8221e4cc2.png)

I think this is a rendering issue. When I shrink the size of the window to the logo only, the CPU load drops from 70 % to 20 % and raises again when I maximize the window.

**Comment by slaweet** [comment]
I think the reason is this subtle animation of the account visual because it has 30 seconds delay:
https://github.com/LiskHQ/lisk-hub/blob/a22e8dbcbac8559216deeb4c1302748a19b23a16/src/components/accountVisual/accountVisual.css#L11-L16

**Comment by webmaster128** [comment]
@ginacontrino When I tried to create an account on https://jenkins.lisk.io/test/lisk-hub/PR-754/#/, I cannot click the 3 missing word buttons on the "Select the missing words to confirm" page. This looks like a serious regression.

Using Chromium Version 65, I can reproduce a 40 % system load with https://lisk.io/hub/index.html#/main/dashboard vs. a 18 % system load using https://jenkins.lisk.io/test/lisk-hub/PR-754/#/dashboard. The original observation was from the electron build, so I would compare the electron apps again when a RC is out.

**Comment by ginacontrino** [comment]
@webmaster128 thank you for your feedback and for notifying us about the button, this needs to be fixed. 

I will get back to the issue when the next RC is out.

**Comment by slaweet** [comment]
Fixed by #754
