### ISSUE TITLE
Handle response error from delegates search by number in main/voting

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#638]
### Expected behaviour

Performing a search in https://lisk.io/hub-rc/#/main/voting by number, should inform the user of no results found whenever the API responds with failure.

### Actual behaviour
 Performing a search by numbers in https://lisk.io/hub-rc/#/main/voting, for a delegate, results in API error, the client does not show `No delegates found` and an error is thrown in the console

![main-votin-search-delegate-by-number](https://user-images.githubusercontent.com/668295/38078151-a45d07d0-333b-11e8-960e-f4e276a25374.png)

### Steps to reproduce
* Go to https://lisk.io/hub-rc/#/main/voting and enter `11` in search field.
* Verify UI doesn't change informing of `No delegates found`
* Verify there are request response errors in browser console.

**Comment by slaweet** [comment]
Solved by migrating to Lisk Core 1.0
