### ISSUE TITLE
Send to this address button doesn't show the expected send form

### ISSUE THREAD

**Issue by reyraa** [LiskHQ/lisk-hub#670]
### Expected behaviour
If you clicked on "Send to this address" button, it should show the Transform form with the address profiled.

### Actual behaviour
It returns to Wallet page and shows "Initialize Lisk ID" form.

### Steps to reproduce
 - Login using any uninitialised account
 - Navigate to an address page, using search or clicking on a render/recipient address in transaction detail page.
 - Click on Send to this address
 - Now instead of Transform/Send form, you see "Initialize Lisk ID" form.

**Comment by itssujan** [comment]
@slaweet/@reyraa  can i start looking at this one?

**Comment by reyraa** [comment]
@itssujan Hi. yes please. we welcome all contributions from our community members.

**Comment by reyraa** [comment]
@itssujan yes, all unassigned tickets. but if you think if would take a day or more, please contact us to make sure no one else is working on it.
