### ISSUE TITLE
Handle not running servers when trying to access a saved account

### ISSUE THREAD

**Issue by ginacontrino** [LiskHQ/lisk-hub#674]
### Expected behaviour
The app should show an error message and/or redirect to the login page when trying to access a saved account with localhost that is down

### Actual behaviour
Currently the whole app breaks when clicking on a saved account with a localhost that is not running

### Steps to reproduce
- Add a new saved account with e.g. `localhost:5000`, 
- then go back to the normal `localhost:4000`
- now open account switcher and try clicking on your account with the `localhost:5000`
- app will break

**Comment by slaweet** [comment]
Saved accounts removed, so closing.
