### ISSUE TITLE
Research launch protocol for the web app

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#684]
Similar to how can Gmail open mailto links

**Comment by michaeltomasik** [comment]
Apparently, protocol `mailto:` opens an application that is assigned to this protocol.
If We want User to make a decision between using the desktop app or website version, We may trigger a pop-up when an app is loading on launching protocol event that asks what version to use.

**Comment by slaweet** [comment]
Not relevant since removing the hosted version. We can re-open in the future if things change.
