### ISSUE TITLE
When verifying passphrase, selected words don't turn green

### ISSUE THREAD

**Issue by punkr0ck** [LiskHQ/lisk-hub#717]
### Expected behaviour
Lisk Hub v0.5.0-rc.1

Missing words to pick, should turn green as in previous versions of hub.

### Actual behaviour
Nothing happens if you pick a word by clicking on it. They are selected but without visual feedback. Tested on latest Firefox and latest Chrome.

### Steps to reproduce
Create new account.

**Comment by alepop** [comment]
The same behaviour in Desktop version
