### ISSUE TITLE
Set up async browserstack tests

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#743]
### Expected behaviour
browserstack tests running simultaneously for different browsers.
### Actual behaviour
Currently, browserstack tests work synchronous way. #428

**Comment by michaeltomasik** [comment]
Please use `428-browserstack-demo` branch to start

**Comment by slaweet** [comment]
Not relevant since removing the hosted version. We can re-open in the future if things change.
