### ISSUE TITLE
Icon font & CSS content values

### ISSUE THREAD

**Issue by hpbaxxtr** [LiskHQ/lisk-hub#764]
### Expected behaviour

Design needs a frictionless workflow to update the iconfont with new icons over time.

We've worked with a grunt script to automate the batch export from .sketch files to SVG and then into a font, described here: https://medium.com/sketch-app-sources/font-icons-workflow-with-sketch-and-grunt-16b161d97c5e
The script builds up on another script, SVG-to-font https://github.com/sapegin/grunt-webfont
Output is a webfont & CSS file. So far, we encountered no problems.

### Actual behaviour

Recently, the mapping between characters in the webfont & CSS content values do not match former versions anymore. Not sure why this is happening. My guess is, that the whole batch of exported SVGs is processed alphabetically & additional icons mess up the order.
This should've happened before though (?!) so I don't know.

### Steps to reproduce

Ask design for .sketch file – it's set up like this:

<img width="400" alt="screen shot 2018-04-25 at 16 00 29" src="https://user-images.githubusercontent.com/34156128/39251723-481d9b00-48a4-11e8-8319-0297f57071d5.png">

Icons are not ordered in any particular way.

**Comment by slaweet** [comment]
@yasharAyari figured this out with @hpbaxxtr
