### ISSUE TITLE
Fix style inconsistencies in settings

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-hub#776]
The button’s text look different. Also the text doesn’t look aligned in the middle (vertically)
![image](https://user-images.githubusercontent.com/1254342/39257336-8f41ec54-48b1-11e8-9f10-27ef44056447.png)
![pasted image at 2018_04_25 05_52 pm](https://user-images.githubusercontent.com/1254342/39257339-912dadfa-48b1-11e8-85d8-e445116db503.png)

**Comment by slaweet** [comment]
Fixed in #776
