### ISSUE TITLE
Hub not saving more than 1 Lisk ID

### ISSUE THREAD

**Issue by Phoenix1969** [LiskHQ/lisk-hub#842]
### Expected behaviour 
Adding Lisk ID's through the "Add a Lisk ID" tab should add the ID to a saved list for later use.

### Actual behaviour 
Adding an ID results in losing any prior ID on Windows version

### Steps to reproduce
Add an ID, close and re-open the app, and go to swich ID's... there will only be 1 there, the last one you used. All other "saved ones" missing.

**Comment by Phoenix1969** [comment]
I noticed this since version 060

**Comment by ginacontrino** [comment]
@Phoenix1969 Could you please provide a bit more information? Did this happen always or only sometimes? I tried to reproduce the situation on windows but it worked fine for me.

**Comment by faival** [comment]
@Phoenix1969 closing this as saved accounts will be removed in version 1.2, users will have followed accounts widget in dashboard.
