### ISSUE TITLE
Goal `e2e-test` should fail with error message in case `dev` goal was not started

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#881]
### Expected behaviour
- If a developer runs `npm run e2e-test` without prior having ran `npm run dev` the goal should fail giving a comprehensive error message.
### Actual behaviour
- No comprehensive error message is shown.

**Comment by slaweet** [comment]
It should also give an error message when lisk-core that it's trying to connect to is not running.

**Comment by Efefefef** [comment]
Well we can not run protractor at all doing a check before
`curl --silent --fail --output /dev/null $(echo $([ -z "$LISK_PORT" ] && echo "http://localhost:4000/api/accounts" || echo http://127.0.0.1:$LISK_PORT/api/accounts)) && curl --silent --fail --output /dev/null $(echo $([ -z "$N" ] && echo "http://localhost:8080" || echo http://127.0.0.1:300$N)) && protractor protractor.conf.js`

Not sure if there is 'beforeEverything' hook in protractor
