### ISSUE TITLE
Typo in update info box

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-hub#888]
### Expected behaviour

Should read "You will be informed **when** it is finished"

### Actual behaviour
![screen shot 2018-06-07 at 10 09 26](https://user-images.githubusercontent.com/11036220/41086918-ab862cd0-6a3b-11e8-9a31-ef5b952bdd0f.png)

### Steps to reproduce

Open Hub after an update has been released and click "Update".

**Comment by slaweet** [comment]
This was fixed in this PR https://github.com/LiskHQ/lisk-hub/pull/811/files
