### ISSUE TITLE
Menu not fully visible

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-hub#889]
### Expected behaviour

I should be able to see the full menu, or if that's not possible I should be able to scroll to see them.

### Actual behaviour
<img width="204" alt="screen shot 2018-06-07 at 10 18 30" src="https://user-images.githubusercontent.com/11036220/41087186-473ba06a-6a3c-11e8-9670-a8e2824bee9f.png">

With delegate features turned on, I can't see the full icon for "Settings" or its label, and cannot scroll it into view, even when Hub is the full size of my screen. What's weirder is that it's obscured by a "More" box which displays the exact same menu items.

### Steps to reproduce

Open Hub, turn on delegate features (but turning them off and using a smaller window produces the same problem).

**Comment by slaweet** [comment]
The menu was updated in 0.9.0, so that this no longer happens: https://ci.lisk.io/test/lisk-hub/0.9.0/
