### ISSUE TITLE
Investigate possible integrations of feedback in lisk existing services

### ISSUE THREAD

**Issue by faival** [LiskHQ/lisk-hub#915]
### Expected behaviour
Find out which available services we could use to gather feedback from lisk-hub users
Possibilities:
- https://gitter.im/LiskHQ/lisk
- https://lisk.chat/home
- slack https://www.npmjs.com/package/react-slack-feedback

- Child of #897

**Comment by slaweet** [comment]
@faival I would look at tools on this list https://www.programmableweb.com/category/surveys/api I think that all of the ones you listed have the issue that users need to have accounts there.

**Comment by slaweet** [comment]
@faival I would also look into tools like https://usabilla.com/

**Comment by faival** [comment]
to check also https://helio.app/

**Comment by faival** [comment]
helio.app --> no API available, all interaction happens through helio.app, form creation, results retrieval, sending of forms to participants.

usabilla --> JS api available, but seems very limited, and only used to trigger actions on the iFrame which is rendered coming from their service. (not so much customization on the look and feel of forms)
- Lots of OOB analytics which might be a sign that the API does user tracking/targeting by IP, geoloc, etc.

**Comment by faival** [comment]
- https://admin.polljoy.com/integrate --> provides sdk but not API, styling achieved through skinning of existing templates.

**Comment by faival** [comment]
* https://www.nicereply.com/ seems to provide a more simplistic API than 

https://developers.google.com/apps-script/api/reference/rest/v1/scripts/run
https://developers.google.com/apps-script/reference/forms/

**Comment by faival** [comment]
- https://www.wufoo.com/wufoo-google-forms/ similar to google forms, injecting iframe for feedback. used by mailchimp

**Comment by faival** [comment]
- https://asknicely.asknice.ly/help/apidocs/survey seems api is only to send surveys via email, or url. and not to post responses in a programatic manner. 

- https://customer.guru/api/documentation/v2, seems to be the same, only programatic API to request send survey by email, or to retrieve responses.

**Comment by faival** [comment]
I would add my vote finally to google node.js scripts api, seems quite powerfull and easy to integrate and maintain. 

created an example for reading from an .xls sheet in this repo.
https://github.com/faival/express-google-sheets
