### ISSUE TITLE
Sign Message Should Verify That Passphrase Used to Sign Message Belongs to Account that User is Logged Into.

### ISSUE THREAD

**Issue by Nimbus76** [LiskHQ/lisk-hub#921]
### Expected behaviour

When a user is logged into an account and signs a message, Sign Message should verify that the passphrase the user enters to sign the message belongs to the account that the user is logged into.  If a passphrase is used that does not belong to the account that is logged into, Sign Message should reject the passphrase and request the user to enter passphrase belonging to the account that the user is logged into.  An additional suggestion that if the user wishes to sign with with a different account, that the user should login to that account, then click the launch protocol that the user has been provided with. 

### Actual behaviour

Sign Message accepts passphrases that do not belong to the account that is logged into.  Sign message then uses the passphrase the user enters to sign the message.  Most importantly, the signed message body shows the Public Key as being the account that the user is logged into, rather than the public key for the account that was used to sign the message.  This will inevitably cause signature verification issues in signature verification systems.

### Steps to reproduce

1.  Open Hub.
2.  Log into an account.
3.  Use a crafted launch protocol link to open the Sign Message page.
4.  Click "Next."
5.  Enter Passphrase from a second account that the user is not logged into and click "Confirm."
6.  Note that the Public Key in the message body belongs to the account that was logged into, not to the account that was used to sign the message.

**Comment by slaweet** [comment]
Fixed in #922
