### ISSUE TITLE
Bug on Sign Message when Lisk ID Is not Locked

### ISSUE THREAD

**Issue by hirishh** [LiskHQ/lisk-hub#979]
### Expected behaviour

To sign correctly a message even if I've just added a new Lisk ID and it's not locked yet

### Actual behaviour

Produced signature is wrong because passphrase used to sign is an empty string.
Bug is here: https://github.com/LiskHQ/lisk-hub/blob/v0.9.0/src/components/signMessage/confirmMessage.js#L66

### Steps to reproduce

- Add a new Lisk-ID (or generate a new one).
- Sign a message
- Verify that the signature is wrong with lisk-js

Best,

hirish

**Comment by slaweet** [comment]
Fixed in `v1.0.0-rc.1`
https://github.com/LiskHQ/lisk-hub/blob/v1.0.0-rc.1/src/components/signMessage/confirmMessage.js#L66
