### ISSUE TITLE
Lisk Hub 0.10.0 does not log into testnet

### ISSUE THREAD

**Issue by Joo5t** [LiskHQ/lisk-hub#983]
I put in my correct testnet passphrase but it couldnt connect. Check screenshot.

![image](https://user-images.githubusercontent.com/20902562/42322533-2ee25ea0-805d-11e8-8dde-8566008bcb9e.png)

**Comment by slaweet** [comment]
Hub 0.10.0 is not compatible with Core 1.0.0, which is since last thursday on Testnet. Core 1.0.0 will come with [Hub 1.0.0](https://github.com/LiskHQ/lisk-hub/projects/37) which is currently in development
